// ═══════════════════════════════════════════════════════════════════════
// ایران - استان‌ها و شهرها
// داده‌های کامل ۳۱ استان ایران
// ═══════════════════════════════════════════════════════════════════════

export interface Province {
  id: string;
  name: string;
  cities: City[];
}

export interface City {
  id: string;
  name: string;
  provinceName: string;
}

export const IRAN_PROVINCES: Province[] = [
  {
    id: 'tehran',
    name: 'تهران',
    cities: [
      { id: 'tehran-1', name: 'تهران', provinceName: 'تهران' },
      { id: 'tehran-2', name: 'ری', provinceName: 'تهران' },
      { id: 'tehran-3', name: 'شهرری', provinceName: 'تهران' },
      { id: 'tehran-4', name: 'اسلامشهر', provinceName: 'تهران' },
      { id: 'tehran-5', name: 'پاکدشت', provinceName: 'تهران' },
      { id: 'tehran-6', name: 'ورامین', provinceName: 'تهران' },
      { id: 'tehran-7', name: 'قدس', provinceName: 'تهران' },
      { id: 'tehran-8', name: 'ملارد', provinceName: 'تهران' },
      { id: 'tehran-9', name: 'رباط‌کریم', provinceName: 'تهران' },
      { id: 'tehran-10', name: 'فیروزکوه', provinceName: 'تهران' },
      { id: 'tehran-11', name: 'دماوند', provinceName: 'تهران' },
      { id: 'tehran-12', name: 'پیشوا', provinceName: 'تهران' },
      { id: 'tehran-13', name: 'پردیس', provinceName: 'تهران' },
      { id: 'tehran-14', name: 'بومهن', provinceName: 'تهران' },
      { id: 'tehran-15', name: 'شمیرانات', provinceName: 'تهران' },
    ],
  },
  {
    id: 'isfahan',
    name: 'اصفهان',
    cities: [
      { id: 'isfahan-1', name: 'اصفهان', provinceName: 'اصفهان' },
      { id: 'isfahan-2', name: 'کاشان', provinceName: 'اصفهان' },
      { id: 'isfahan-3', name: 'خمینی‌شهر', provinceName: 'اصفهان' },
      { id: 'isfahan-4', name: 'نجف‌آباد', provinceName: 'اصفهان' },
      { id: 'isfahan-5', name: 'شاهین‌شهر', provinceName: 'اصفهان' },
      { id: 'isfahan-6', name: 'فلاورجان', provinceName: 'اصفهان' },
      { id: 'isfahan-7', name: 'لنجان', provinceName: 'اصفهان' },
      { id: 'isfahan-8', name: 'مبارکه', provinceName: 'اصفهان' },
      { id: 'isfahan-9', name: 'نطنز', provinceName: 'اصفهان' },
      { id: 'isfahan-10', name: 'اردستان', provinceName: 'اصفهان' },
      { id: 'isfahan-11', name: 'تیران', provinceName: 'اصفهان' },
      { id: 'isfahan-12', name: 'گلپایگان', provinceName: 'اصفهان' },
      { id: 'isfahan-13', name: 'نائین', provinceName: 'اصفهان' },
      { id: 'isfahan-14', name: 'سمیرم', provinceName: 'اصفهان' },
    ],
  },
  {
    id: 'khorasan-razavi',
    name: 'خراسان رضوی',
    cities: [
      { id: 'khorasan-razavi-1', name: 'مشهد', provinceName: 'خراسان رضوی' },
      { id: 'khorasan-razavi-2', name: 'نیشابور', provinceName: 'خراسان رضوی' },
      { id: 'khorasan-razavi-3', name: 'سبزوار', provinceName: 'خراسان رضوی' },
      { id: 'khorasan-razavi-4', name: 'تربت‌حیدریه', provinceName: 'خراسان رضوی' },
      { id: 'khorasan-razavi-5', name: 'قوچان', provinceName: 'خراسان رضوی' },
      { id: 'khorasan-razavi-6', name: 'کاشمر', provinceName: 'خراسان رضوی' },
      { id: 'khorasan-razavi-7', name: 'گناباد', provinceName: 'خراسان رضوی' },
      { id: 'khorasan-razavi-8', name: 'تربت‌جام', provinceName: 'خراسان رضوی' },
      { id: 'khorasan-razavi-9', name: 'تایباد', provinceName: 'خراسان رضوی' },
      { id: 'khorasan-razavi-10', name: 'خواف', provinceName: 'خراسان رضوی' },
      { id: 'khorasan-razavi-11', name: 'فریمان', provinceName: 'خراسان رضوی' },
      { id: 'khorasan-razavi-12', name: 'درگز', provinceName: 'خراسان رضوی' },
      { id: 'khorasan-razavi-13', name: 'چناران', provinceName: 'خراسان رضوی' },
    ],
  },
  {
    id: 'fars',
    name: 'فارس',
    cities: [
      { id: 'fars-1', name: 'شیراز', provinceName: 'فارس' },
      { id: 'fars-2', name: 'مرودشت', provinceName: 'فارس' },
      { id: 'fars-3', name: 'کازرون', provinceName: 'فارس' },
      { id: 'fars-4', name: 'جهرم', provinceName: 'فارس' },
      { id: 'fars-5', name: 'فسا', provinceName: 'فارس' },
      { id: 'fars-6', name: 'لار', provinceName: 'فارس' },
      { id: 'fars-7', name: 'داراب', provinceName: 'فارس' },
      { id: 'fars-8', name: 'آباده', provinceName: 'فارس' },
      { id: 'fars-9', name: 'نی‌ریز', provinceName: 'فارس' },
      { id: 'fars-10', name: 'فیروزآباد', provinceName: 'فارس' },
      { id: 'fars-11', name: 'ممسنی', provinceName: 'فارس' },
      { id: 'fars-12', name: 'نورآباد', provinceName: 'فارس' },
      { id: 'fars-13', name: 'اقلید', provinceName: 'فارس' },
      { id: 'fars-14', name: 'خنج', provinceName: 'فارس' },
    ],
  },
  {
    id: 'azarbaijan-east',
    name: 'آذربایجان شرقی',
    cities: [
      { id: 'azarbaijan-east-1', name: 'تبریز', provinceName: 'آذربایجان شرقی' },
      { id: 'azarbaijan-east-2', name: 'مراغه', provinceName: 'آذربایجان شرقی' },
      { id: 'azarbaijan-east-3', name: 'مرند', provinceName: 'آذربایجان شرقی' },
      { id: 'azarbaijan-east-4', name: 'میانه', provinceName: 'آذربایجان شرقی' },
      { id: 'azarbaijan-east-5', name: 'اهر', provinceName: 'آذربایجان شرقی' },
      { id: 'azarbaijan-east-6', name: 'بناب', provinceName: 'آذربایجان شرقی' },
      { id: 'azarbaijan-east-7', name: 'سراب', provinceName: 'آذربایجان شرقی' },
      { id: 'azarbaijan-east-8', name: 'اسکو', provinceName: 'آذربایجان شرقی' },
      { id: 'azarbaijan-east-9', name: 'بستان‌آباد', provinceName: 'آذربایجان شرقی' },
      { id: 'azarbaijan-east-10', name: 'شبستر', provinceName: 'آذربایجان شرقی' },
      { id: 'azarbaijan-east-11', name: 'هشترود', provinceName: 'آذربایجان شرقی' },
      { id: 'azarbaijan-east-12', name: 'ملکان', provinceName: 'آذربایجان شرقی' },
      { id: 'azarbaijan-east-13', name: 'جلفا', provinceName: 'آذربایجان شرقی' },
    ],
  },
  {
    id: 'azarbaijan-west',
    name: 'آذربایجان غربی',
    cities: [
      { id: 'azarbaijan-west-1', name: 'ارومیه', provinceName: 'آذربایجان غربی' },
      { id: 'azarbaijan-west-2', name: 'خوی', provinceName: 'آذربایجان غربی' },
      { id: 'azarbaijan-west-3', name: 'میاندوآب', provinceName: 'آذربایجان غربی' },
      { id: 'azarbaijan-west-4', name: 'بوکان', provinceName: 'آذربایجان غربی' },
      { id: 'azarbaijan-west-5', name: 'مهاباد', provinceName: 'آذربایجان غربی' },
      { id: 'azarbaijan-west-6', name: 'سلماس', provinceName: 'آذربایجان غربی' },
      { id: 'azarbaijan-west-7', name: 'نقده', provinceName: 'آذربایجان غربی' },
      { id: 'azarbaijan-west-8', name: 'پیرانشهر', provinceName: 'آذربایجان غربی' },
      { id: 'azarbaijan-west-9', name: 'ماکو', provinceName: 'آذربایجان غربی' },
      { id: 'azarbaijan-west-10', name: 'تکاب', provinceName: 'آذربایجان غربی' },
      { id: 'azarbaijan-west-11', name: 'شاهین‌دژ', provinceName: 'آذربایجان غربی' },
    ],
  },
  {
    id: 'kermanshah',
    name: 'کرمانشاه',
    cities: [
      { id: 'kermanshah-1', name: 'کرمانشاه', provinceName: 'کرمانشاه' },
      { id: 'kermanshah-2', name: 'اسلام‌آباد غرب', provinceName: 'کرمانشاه' },
      { id: 'kermanshah-3', name: 'سنقر', provinceName: 'کرمانشاه' },
      { id: 'kermanshah-4', name: 'کنگاور', provinceName: 'کرمانشاه' },
      { id: 'kermanshah-5', name: 'هرسین', provinceName: 'کرمانشاه' },
      { id: 'kermanshah-6', name: 'جوانرود', provinceName: 'کرمانشاه' },
      { id: 'kermanshah-7', name: 'پاوه', provinceName: 'کرمانشاه' },
      { id: 'kermanshah-8', name: 'گیلان‌غرب', provinceName: 'کرمانشاه' },
      { id: 'kermanshah-9', name: 'سرپل‌ذهاب', provinceName: 'کرمانشاه' },
      { id: 'kermanshah-10', name: 'صحنه', provinceName: 'کرمانشاه' },
      { id: 'kermanshah-11', name: 'قیسوند', provinceName: 'کرمانشاه' },
      { id: 'kermanshah-12', name: 'سرمله', provinceName: 'کرمانشاه' },
    ],
  },
  {
    id: 'gilan',
    name: 'گیلان',
    cities: [
      { id: 'gilan-1', name: 'رشت', provinceName: 'گیلان' },
      { id: 'gilan-2', name: 'بندرانزلی', provinceName: 'گیلان' },
      { id: 'gilan-3', name: 'لاهیجان', provinceName: 'گیلان' },
      { id: 'gilan-4', name: 'آستارا', provinceName: 'گیلان' },
      { id: 'gilan-5', name: 'تالش', provinceName: 'گیلان' },
      { id: 'gilan-6', name: 'رودسر', provinceName: 'گیلان' },
      { id: 'gilan-7', name: 'لنگرود', provinceName: 'گیلان' },
      { id: 'gilan-8', name: 'صومعه‌سرا', provinceName: 'گیلان' },
      { id: 'gilan-9', name: 'آستانه‌اشرفیه', provinceName: 'گیلان' },
      { id: 'gilan-10', name: 'فومن', provinceName: 'گیلان' },
      { id: 'gilan-11', name: 'شفت', provinceName: 'گیلان' },
      { id: 'gilan-12', name: 'رضوانشهر', provinceName: 'گیلان' },
      { id: 'gilan-13', name: 'املش', provinceName: 'گیلان' },
      { id: 'gilan-14', name: 'سیاهکل', provinceName: 'گیلان' },
      { id: 'gilan-15', name: 'هشتپر', provinceName: 'گیلان' },
      { id: 'gilan-16', name: 'رودبار', provinceName: 'گیلان' },
      { id: 'gilan-17', name: 'ماسال', provinceName: 'گیلان' },
      { id: 'gilan-18', name: 'آق‌سو', provinceName: 'گیلان' },
    ],
  },
  {
    id: 'mazandaran',
    name: 'مازندران',
    cities: [
      { id: 'mazandaran-1', name: 'ساری', provinceName: 'مازندران' },
      { id: 'mazandaran-2', name: 'بابل', provinceName: 'مازندران' },
      { id: 'mazandaran-3', name: 'آمل', provinceName: 'مازندران' },
      { id: 'mazandaran-4', name: 'قائمشهر', provinceName: 'مازندران' },
      { id: 'mazandaran-5', name: 'بهشهر', provinceName: 'مازندران' },
      { id: 'mazandaran-6', name: 'تنکابن', provinceName: 'مازندران' },
      { id: 'mazandaran-7', name: 'نوشهر', provinceName: 'مازندران' },
      { id: 'mazandaran-8', name: 'چالوس', provinceName: 'مازندران' },
      { id: 'mazandaran-9', name: 'نکا', provinceName: 'مازندران' },
      { id: 'mazandaran-10', name: 'بابلسر', provinceName: 'مازندران' },
      { id: 'mazandaran-11', name: 'محمودآباد', provinceName: 'مازندران' },
      { id: 'mazandaran-12', name: 'رامسر', provinceName: 'مازندران' },
      { id: 'mazandaran-13', name: 'فریدونکنار', provinceName: 'مازندران' },
      { id: 'mazandaran-14', name: 'جویبار', provinceName: 'مازندران' },
      { id: 'mazandaran-15', name: 'سوادکوه', provinceName: 'مازندران' },
      { id: 'mazandaran-16', name: 'میدان‌سر', provinceName: 'مازندران' },
    ],
  },
  {
    id: 'khuzestan',
    name: 'خوزستان',
    cities: [
      { id: 'khuzestan-1', name: 'اهواز', provinceName: 'خوزستان' },
      { id: 'khuzestan-2', name: 'دزفول', provinceName: 'خوزستان' },
      { id: 'khuzestan-3', name: 'آبادان', provinceName: 'خوزستان' },
      { id: 'khuzestan-4', name: 'خرمشهر', provinceName: 'خوزستان' },
      { id: 'khuzestan-5', name: 'شوشتر', provinceName: 'خوزستان' },
      { id: 'khuzestan-6', name: 'بهبهان', provinceName: 'خوزستان' },
      { id: 'khuzestan-7', name: 'ماهشهر', provinceName: 'خوزستان' },
      { id: 'khuzestan-8', name: 'ایذه', provinceName: 'خوزستان' },
      { id: 'khuzestan-9', name: 'مسجدسلیمان', provinceName: 'خوزستان' },
      { id: 'khuzestan-10', name: 'اندیمشک', provinceName: 'خوزستان' },
      { id: 'khuzestan-11', name: 'شادگان', provinceName: 'خوزستان' },
      { id: 'khuzestan-12', name: 'رامهرمز', provinceName: 'خوزستان' },
      { id: 'khuzestan-13', name: 'لتیان', provinceName: 'خوزستان' },
    ],
  },
  {
    id: 'kerman',
    name: 'کرمان',
    cities: [
      { id: 'kerman-1', name: 'کرمان', provinceName: 'کرمان' },
      { id: 'kerman-2', name: 'رفسنجان', provinceName: 'کرمان' },
      { id: 'kerman-3', name: 'سیرجان', provinceName: 'کرمان' },
      { id: 'kerman-4', name: 'جیرفت', provinceName: 'کرمان' },
      { id: 'kerman-5', name: 'بم', provinceName: 'کرمان' },
      { id: 'kerman-6', name: 'زرند', provinceName: 'کرمان' },
      { id: 'kerman-7', name: 'کهنوج', provinceName: 'کرمان' },
      { id: 'kerman-8', name: 'بردسیر', provinceName: 'کرمان' },
      { id: 'kerman-9', name: 'بافت', provinceName: 'کرمان' },
      { id: 'kerman-10', name: 'راور', provinceName: 'کرمان' },
      { id: 'kerman-11', name: 'شهربابک', provinceName: 'کرمان' },
      { id: 'kerman-12', name: 'عنبرآباد', provinceName: 'کرمان' },
    ],
  },
  {
    id: 'hormozgan',
    name: 'هرمزگان',
    cities: [
      { id: 'hormozgan-1', name: 'بندرعباس', provinceName: 'هرمزگان' },
      { id: 'hormozgan-2', name: 'میناب', provinceName: 'هرمزگان' },
      { id: 'hormozgan-3', name: 'بندرلنگه', provinceName: 'هرمزگان' },
      { id: 'hormozgan-4', name: 'قشم', provinceName: 'هرمزگان' },
      { id: 'hormozgan-5', name: 'کیش', provinceName: 'هرمزگان' },
      { id: 'hormozgan-6', name: 'حاجی‌آباد', provinceName: 'هرمزگان' },
      { id: 'hormozgan-7', name: 'رودان', provinceName: 'هرمزگان' },
      { id: 'hormozgan-8', name: 'بستک', provinceName: 'هرمزگان' },
      { id: 'hormozgan-9', name: 'جاسک', provinceName: 'هرمزگان' },
      { id: 'hormozgan-10', name: 'پارسیان', provinceName: 'هرمزگان' },
      { id: 'hormozgan-11', name: 'بشاگرد', provinceName: 'هرمزگان' },
      { id: 'hormozgan-12', name: 'گاوبندی', provinceName: 'هرمزگان' },
    ],
  },
  {
    id: 'yazd',
    name: 'یزد',
    cities: [
      { id: 'yazd-1', name: 'یزد', provinceName: 'یزد' },
      { id: 'yazd-2', name: 'میبد', provinceName: 'یزد' },
      { id: 'yazd-3', name: 'اردکان', provinceName: 'یزد' },
      { id: 'yazd-4', name: 'تفت', provinceName: 'یزد' },
      { id: 'yazd-5', name: 'مهریز', provinceName: 'یزد' },
      { id: 'yazd-6', name: 'بافق', provinceName: 'یزد' },
      { id: 'yazd-7', name: 'ابرکوه', provinceName: 'یزد' },
      { id: 'yazd-8', name: 'هرات', provinceName: 'یزد' },
      { id: 'yazd-9', name: 'اشکذر', provinceName: 'یزد' },
      { id: 'yazd-10', name: 'نیر', provinceName: 'یزد' },
    ],
  },
  {
    id: ' Kurdistan',
    name: 'کردستان',
    cities: [
      { id: 'kurdistan-1', name: 'سنندج', provinceName: 'کردستان' },
      { id: 'kurdistan-2', name: 'سقز', provinceName: 'کردستان' },
      { id: 'kurdistan-3', name: 'مریوان', provinceName: 'کردستان' },
      { id: 'kurdistan-4', name: 'بانه', provinceName: 'کردستان' },
      { id: 'kurdistan-5', name: 'قروه', provinceName: 'کردستان' },
      { id: 'kurdistan-6', name: 'بیجار', provinceName: 'کردستان' },
      { id: 'kurdistan-7', name: 'کامیاران', provinceName: 'کردستان' },
      { id: 'kurdistan-8', name: 'دیواندره', provinceName: 'کردستان' },
      { id: 'kurdistan-9', name: 'دهگلان', provinceName: 'کردستان' },
    ],
  },
  {
    id: 'hamedan',
    name: 'همدان',
    cities: [
      { id: 'hamedan-1', name: 'همدان', provinceName: 'همدان' },
      { id: 'hamedan-2', name: 'ملایر', provinceName: 'همدان' },
      { id: 'hamedan-3', name: 'نهاوند', provinceName: 'همدان' },
      { id: 'hamedan-4', name: 'تویسرکان', provinceName: 'همدان' },
      { id: 'hamedan-5', name: 'اسدآباد', provinceName: 'همدان' },
      { id: 'hamedan-6', name: 'بهار', provinceName: 'همدان' },
      { id: 'hamedan-7', name: 'کبودرآهنگ', provinceName: 'همدان' },
      { id: 'hamedan-8', name: 'رزن', provinceName: 'همدان' },
      { id: 'hamedan-9', name: 'فامنین', provinceName: 'همدان' },
      { id: 'hamedan-10', name: 'درگزین', provinceName: 'همدان' },
    ],
  },
  {
    id: 'golestan',
    name: 'گلستان',
    cities: [
      { id: 'golestan-1', name: 'گرگان', provinceName: 'گلستان' },
      { id: 'golestan-2', name: 'گنبدکاووس', provinceName: 'گلستان' },
      { id: 'golestan-3', name: 'آق‌قلا', provinceName: 'گلستان' },
      { id: 'golestan-4', name: 'علی‌آباد کتول', provinceName: 'گلستان' },
      { id: 'golestan-5', name: 'مینودشت', provinceName: 'گلستان' },
      { id: 'golestan-6', name: 'کردکوی', provinceName: 'گلستان' },
      { id: 'golestan-7', name: 'بندرترکمن', provinceName: 'گلستان' },
      { id: 'golestan-8', name: 'آزادشهر', provinceName: 'گلستان' },
      { id: 'golestan-9', name: 'رامیان', provinceName: 'گلستان' },
      { id: 'golestan-10', name: 'کلاله', provinceName: 'گلستان' },
      { id: 'golestan-11', name: 'جلین', provinceName: 'گلستان' },
      { id: 'golestan-12', name: 'صومعه‌سرا', provinceName: 'گلستان' },
      { id: 'golestan-13', name: 'اینچه‌برون', provinceName: 'گلستان' },
      { id: 'golestan-14', name: 'دلند', provinceName: 'گلستان' },
    ],
  },
  {
    id: 'markazi',
    name: 'مرکزی',
    cities: [
      { id: 'markazi-1', name: 'اراک', provinceName: 'مرکزی' },
      { id: 'markazi-2', name: 'ساوه', provinceName: 'مرکزی' },
      { id: 'markazi-3', name: 'خمین', provinceName: 'مرکزی' },
      { id: 'markazi-4', name: 'دلیجان', provinceName: 'مرکزی' },
      { id: 'markazi-5', name: 'محلات', provinceName: 'مرکزی' },
      { id: 'markazi-6', name: 'تفرش', provinceName: 'مرکزی' },
      { id: 'markazi-7', name: 'شازند', provinceName: 'مرکزی' },
      { id: 'markazi-8', name: 'آشتیان', provinceName: 'مرکزی' },
      { id: 'markazi-9', name: 'کمیجان', provinceName: 'مرکزی' },
      { id: 'markazi-10', name: 'زرندیه', provinceName: 'مرکزی' },
    ],
  },
  {
    id: 'semnan',
    name: 'سمنان',
    cities: [
      { id: 'semnan-1', name: 'سمنان', provinceName: 'سمنان' },
      { id: 'semnan-2', name: 'شاهرود', provinceName: 'سمنان' },
      { id: 'semnan-3', name: 'دامغان', provinceName: 'سمنان' },
      { id: 'semnan-4', name: 'گرمسار', provinceName: 'سمنان' },
      { id: 'semnan-5', name: 'مهدیشهر', provinceName: 'سمنان' },
      { id: 'semnan-6', name: 'آرادان', provinceName: 'سمنان' },
      { id: 'semnan-7', name: 'سرخه', provinceName: 'سمنان' },
      { id: 'semnan-8', name: 'میامی', provinceName: 'سمنان' },
    ],
  },
  {
    id: 'lorestan',
    name: 'لرستان',
    cities: [
      { id: 'lorestan-1', name: 'خرم‌آباد', provinceName: 'لرستان' },
      { id: 'lorestan-2', name: 'بروجرد', provinceName: 'لرستان' },
      { id: 'lorestan-3', name: 'دورود', provinceName: 'لرستان' },
      { id: 'lorestan-4', name: 'الیگودرز', provinceName: 'لرستان' },
      { id: 'lorestan-5', name: 'کوهدشت', provinceName: 'لرستان' },
      { id: 'lorestan-6', name: 'ازنا', provinceName: 'لرستان' },
      { id: 'lorestan-7', name: 'نورآباد', provinceName: 'لرستان' },
      { id: 'lorestan-8', name: 'الشتر', provinceName: 'لرستان' },
      { id: 'lorestan-9', name: 'پلدختر', provinceName: 'لرستان' },
      { id: 'lorestan-10', name: 'رومشکان', provinceName: 'لرستان' },
    ],
  },
  {
    id: 'bushehr',
    name: 'بوشهر',
    cities: [
      { id: 'bushehr-1', name: 'بوشهر', provinceName: 'بوشهر' },
      { id: 'bushehr-2', name: 'برازجان', provinceName: 'بوشهر' },
      { id: 'bushehr-3', name: 'کنگان', provinceName: 'بوشهر' },
      { id: 'bushehr-4', name: 'دیّر', provinceName: 'بوشهر' },
      { id: 'bushehr-5', name: 'گناوه', provinceName: 'بوشهر' },
      { id: 'bushehr-6', name: 'دشتی', provinceName: 'بوشهر' },
      { id: 'bushehr-7', name: 'جم', provinceName: 'بوشهر' },
      { id: 'bushehr-8', name: 'عسلویه', provinceName: 'بوشهر' },
      { id: 'bushehr-9', name: 'تنگستان', provinceName: 'بوشهر' },
      { id: 'bushehr-10', name: 'خورموج', provinceName: 'بوشهر' },
    ],
  },
  {
    id: 'zanjan',
    name: 'زنجان',
    cities: [
      { id: 'zanjan-1', name: 'زنجان', provinceName: 'زنجان' },
      { id: 'zanjan-2', name: 'ابهر', provinceName: 'زنجان' },
      { id: 'zanjan-3', name: 'خرمدره', provinceName: 'زنجان' },
      { id: 'zanjan-4', name: 'سلطانیه', provinceName: 'زنجان' },
      { id: 'zanjan-5', name: 'ماه‌نشان', provinceName: 'زنجان' },
      { id: 'zanjan-6', name: 'طارم', provinceName: 'زنجان' },
      { id: 'zanjan-7', name: 'ایجرود', provinceName: 'زنجان' },
      { id: 'zanjan-8', name: 'خدابنده', provinceName: 'زنجان' },
    ],
  },
  {
    id: 'ardabil',
    name: 'اردبیل',
    cities: [
      { id: 'ardabil-1', name: 'اردبیل', provinceName: 'اردبیل' },
      { id: 'ardabil-2', name: 'پارس‌آباد', provinceName: 'اردبیل' },
      { id: 'ardabil-3', name: 'مشکین‌شهر', provinceName: 'اردبیل' },
      { id: 'ardabil-4', name: 'خلخال', provinceName: 'اردبیل' },
      { id: 'ardabil-5', name: 'بیله‌سوار', provinceName: 'اردبیل' },
      { id: 'ardabil-6', name: 'نمین', provinceName: 'اردبیل' },
      { id: 'ardabil-7', name: 'گرمی', provinceName: 'اردبیل' },
      { id: 'ardabil-8', name: 'نیر', provinceName: 'اردبیل' },
      { id: 'ardabil-9', name: 'کوثر', provinceName: 'اردبیل' },
      { id: 'ardabil-10', name: 'سرعین', provinceName: 'اردبیل' },
    ],
  },
  {
    id: 'qazvin',
    name: 'قزوین',
    cities: [
      { id: 'qazvin-1', name: 'قزوین', provinceName: 'قزوین' },
      { id: 'qazvin-2', name: 'تاکستان', provinceName: 'قزوین' },
      { id: 'qazvin-3', name: 'آبیک', provinceName: 'قزوین' },
      { id: 'qazvin-4', name: 'بوئین‌زهرا', provinceName: 'قزوین' },
      { id: 'qazvin-5', name: 'البرز', provinceName: 'قزوین' },
      { id: 'qazvin-6', name: 'آوج', provinceName: 'قزوین' },
    ],
  },
  {
    id: 'ilam',
    name: 'ایلام',
    cities: [
      { id: 'ilam-1', name: 'ایلام', provinceName: 'ایلام' },
      { id: 'ilam-2', name: 'دهلران', provinceName: 'ایلام' },
      { id: 'ilam-3', name: 'ایوان', provinceName: 'ایلام' },
      { id: 'ilam-4', name: 'آبدانان', provinceName: 'ایلام' },
      { id: 'ilam-5', name: 'مهران', provinceName: 'ایلام' },
      { id: 'ilam-6', name: 'دره‌شهر', provinceName: 'ایلام' },
      { id: 'ilam-7', name: 'سرابله', provinceName: 'ایلام' },
      { id: 'ilam-8', name: 'چرداول', provinceName: 'ایلام' },
    ],
  },
  {
    id: 'kohgiluyeh',
    name: 'کهگیلویه و بویراحمد',
    cities: [
      { id: 'kohgiluyeh-1', name: 'یاسوج', provinceName: 'کهگیلویه و بویراحمد' },
      { id: 'kohgiluyeh-2', name: 'گچساران', provinceName: 'کهگیلویه و بویراحمد' },
      { id: 'kohgiluyeh-3', name: 'دهدشت', provinceName: 'کهگیلویه و بویراحمد' },
      { id: 'kohgiluyeh-4', name: 'دوگنبدان', provinceName: 'کهگیلویه و بویراحمد' },
      { id: 'kohgiluyeh-5', name: 'لیکک', provinceName: 'کهگیلویه و بویراحمد' },
      { id: 'kohgiluyeh-6', name: 'باشت', provinceName: 'کهگیلویه و بویراحمد' },
      { id: 'kohgiluyeh-7', name: 'سی‌سخت', provinceName: 'کهگیلویه و بویراحمد' },
    ],
  },
  {
    id: 'south-khorasan',
    name: 'خراسان جنوبی',
    cities: [
      { id: 'south-khorasan-1', name: 'بیرجند', provinceName: 'خراسان جنوبی' },
      { id: 'south-khorasan-2', name: 'قائن', provinceName: 'خراسان جنوبی' },
      { id: 'south-khorasan-3', name: 'طبس', provinceName: 'خراسان جنوبی' },
      { id: 'south-khorasan-4', name: 'فردوس', provinceName: 'خراسان جنوبی' },
      { id: 'south-khorasan-5', name: 'نهبندان', provinceName: 'خراسان جنوبی' },
      { id: 'south-khorasan-6', name: 'سربیشه', provinceName: 'خراسان جنوبی' },
      { id: 'south-khorasan-7', name: 'بشرویه', provinceName: 'خراسان جنوبی' },
      { id: 'south-khorasan-8', name: 'خوسف', provinceName: 'خراسان جنوبی' },
    ],
  },
  {
    id: 'north-khorasan',
    name: 'خراسان شمالی',
    cities: [
      { id: 'north-khorasan-1', name: 'بجنورد', provinceName: 'خراسان شمالی' },
      { id: 'north-khorasan-2', name: 'شیروان', provinceName: 'خراسان شمالی' },
      { id: 'north-khorasan-3', name: 'اسفراین', provinceName: 'خراسان شمالی' },
      { id: 'north-khorasan-4', name: 'جاجرم', provinceName: 'خراسان شمالی' },
      { id: 'north-khorasan-5', name: 'آشخانه', provinceName: 'خراسان شمالی' },
      { id: 'north-khorasan-6', name: 'فاروج', provinceName: 'خراسان شمالی' },
      { id: 'north-khorasan-7', name: 'گرمه', provinceName: 'خراسان شمالی' },
      { id: 'north-khorasan-8', name: 'راز و جرگلان', provinceName: 'خراسان شمالی' },
    ],
  },
  {
    id: 'sistan',
    name: 'سیستان و بلوچستان',
    cities: [
      { id: 'sistan-1', name: 'زاهدان', provinceName: 'سیستان و بلوچستان' },
      { id: 'sistan-2', name: 'چابهار', provinceName: 'سیستان و بلوچستان' },
      { id: 'sistan-3', name: 'زابل', provinceName: 'سیستان و بلوچستان' },
      { id: 'sistan-4', name: 'ایرانشهر', provinceName: 'سیستان و بلوچستان' },
      { id: 'sistan-5', name: 'سراوان', provinceName: 'سیستان و بلوچستان' },
      { id: 'sistan-6', name: 'خاش', provinceName: 'سیستان و بلوچستان' },
      { id: 'sistan-7', name: 'نیکشهر', provinceName: 'سیستان و بلوچستان' },
      { id: 'sistan-8', name: 'کنارک', provinceName: 'سیستان و بلوچستان' },
      { id: 'sistan-9', name: 'دلگان', provinceName: 'سیستان و بلوچستان' },
      { id: 'sistan-10', name: 'قصرقند', provinceName: 'سیستان و بلوچستان' },
      { id: 'sistan-11', name: 'راسک', provinceName: 'سیستان و بلوچستان' },
    ],
  },
  {
    id: 'alborz',
    name: 'البرز',
    cities: [
      { id: 'alborz-1', name: 'کرج', provinceName: 'البرز' },
      { id: 'alborz-2', name: 'فردیس', provinceName: 'البرز' },
      { id: 'alborz-3', name: 'نظرآباد', provinceName: 'البرز' },
      { id: 'alborz-4', name: 'اشتهارد', provinceName: 'البرز' },
      { id: 'alborz-5', name: 'طالقان', provinceName: 'البرز' },
      { id: 'alborz-6', name: 'هشتگرد', provinceName: 'البرز' },
      { id: 'alborz-7', name: 'محمدشهر', provinceName: 'البرز' },
      { id: 'alborz-8', name: 'چهارباغ', provinceName: 'البرز' },
    ],
  },
  {
    id: 'south-khorasan-2',
    name: 'خراسان جنوبی',
    cities: [],
  },
];

// ═══════════════════════════════════════════════════════════════════════
// Helper: Get all city names flat
// ═══════════════════════════════════════════════════════════════════════

export const ALL_CITIES: string[] = IRAN_PROVINCES.flatMap((p) =>
  p.cities.map((c) => c.name)
);

export const ALL_PROVINCES: string[] = IRAN_PROVINCES.map((p) => p.name);

// Remove duplicate province
const uniqueProvinces = [...new Set(ALL_PROVINCES)];
export { uniqueProvinces as ALL_PROVINCES_UNIQUE };

// Get cities by province name
export function getCitiesByProvince(provinceName: string): City[] {
  const province = IRAN_PROVINCES.find((p) => p.name === provinceName);
  return province?.cities ?? [];
}

// Get all popular cities (province capitals)
export const POPULAR_CITIES: string[] = [
  'تهران',
  'اصفهان',
  'مشهد',
  'شیراز',
  'تبریز',
  'اهواز',
  'کرمانشاه',
  'رشت',
  'ساری',
  'کرمان',
  'یزد',
  'اراک',
  'بندرعباس',
  'همدان',
  'سنندج',
  'گرگان',
  'زنجان',
  'اردبیل',
  'بجنورد',
  'زاهدان',
  'کرج',
  'قزوین',
  'سمنان',
  'بوشهر',
  'خرم‌آباد',
  'ایلام',
  'بیرجند',
  'یاسوج',
  'قائن',
  'چابهار',
  'کیش',
  'قشم',
  'نوشهر',
  'چالوس',
  'رامسر',
];
