import type { CategoryFilterSpec } from './types';
import {
  AMENITIES,
  BATHROOM_COUNT,
  BUILDING_AGE_CHIPS,
  CABINET_TYPE,
  COOLING,
  DEED_TYPE,
  FAMILY_COUNT,
  CONDITION,
  DEAL_TYPE_PRODUCT,
  DEAL_TYPE_PROPERTY,
  DEAL_TYPE_VEHICLE,
  DELIVERY_PRE_SALE,
  EMPLOYMENT_TYPE,
  EXPERIENCE,
  FACADE_TYPE,
  GUEST_COUNT,
  HEATING,
  LAND_USE,
  MOVE_IN_WHEN,
  ORIENTATION,
  PARKING_COUNT,
  PET_TYPE,
  POSTER_KIND,
  PROPERTY_KIND,
  RAM_OPTIONS,
  ROLE_TYPE,
  ROOMS,
  SERVICE_WHEN,
  SHORT_TERM_AMENITIES,
  SOCIAL_TYPE,
  STORAGE_MOBILE,
  VEHICLE_KIND,
} from './options';

const G = { browse: true, intake: true } as const;
const C = { browse: true, intake: true, intakeTier: 'critical' as const };

/** Shared built-property amenities & systems (sale + rent residential/commercial). */
const BUILT_PROPERTY_EXTRAS: CategoryFilterSpec = [
  {
    key: 'buildingAge',
    label: 'سن بنا',
    kind: 'chips',
    options: [...BUILDING_AGE_CHIPS],
    ...G,
  },
  {
    key: 'totalFloors',
    label: 'تعداد کل طبقات',
    kind: 'range',
    ...G,
  },
  {
    key: 'unitCount',
    label: 'تعداد واحد در طبقه',
    kind: 'range',
    browse: false,
    intake: true,
  },
  {
    key: 'parkingCount',
    label: 'تعداد پارکینگ',
    kind: 'chips',
    options: [...PARKING_COUNT],
    ...G,
  },
  {
    key: 'bathroomCount',
    label: 'تعداد سرویس بهداشتی',
    kind: 'chips',
    options: [...BATHROOM_COUNT],
    browse: false,
    intake: true,
  },
  {
    key: 'orientation',
    label: 'جهت ساختمان',
    kind: 'chips',
    options: [...ORIENTATION],
    browse: false,
    intake: true,
  },
  {
    key: 'facadeType',
    label: 'نوع نما',
    kind: 'chips',
    options: [...FACADE_TYPE],
    browse: false,
    intake: true,
  },
  {
    key: 'heating',
    label: 'گرمایش',
    kind: 'chips',
    options: [...HEATING],
    browse: false,
    intake: true,
  },
  {
    key: 'cooling',
    label: 'سرمایش',
    kind: 'chips',
    options: [...COOLING],
    browse: false,
    intake: true,
  },
  {
    key: 'cabinetType',
    label: 'کابینت',
    kind: 'chips',
    options: [...CABINET_TYPE],
    browse: false,
    intake: true,
  },
  {
    key: 'posterKind',
    label: 'آگهی‌دهنده',
    kind: 'chips',
    options: [...POSTER_KIND],
    browse: false,
    intake: true,
  },
  {
    key: 'moveInWhen',
    label: 'زمان تحویل / جابجایی',
    kind: 'chips',
    options: [...MOVE_IN_WHEN],
    browse: false,
    intake: true,
  },
];

const SALE_RESIDENTIAL_SPEC: CategoryFilterSpec = [
  { key: 'dealType', label: 'نوع معامله', kind: 'chips', options: [...DEAL_TYPE_PROPERTY], required: true, ...C },
  { key: 'budget', label: 'بودجه / قیمت (تومان)', kind: 'range', browse: true, intake: true },
  {
    key: 'areaMin',
    label: 'حداقل متراژ (متر)',
    kind: 'range',
    urlParam: 'area',
    ...G,
  },
  {
    key: 'areaMax',
    label: 'حداکثر متراژ (متر)',
    kind: 'range',
    urlParam: 'area',
    ...G,
  },
  {
    key: 'pricePerMeterMin',
    label: 'حداقل قیمت هر متر (تومان)',
    kind: 'range',
    urlParam: 'pricePerMeter',
    ...G,
  },
  {
    key: 'pricePerMeterMax',
    label: 'حداکثر قیمت هر متر (تومان)',
    kind: 'range',
    urlParam: 'pricePerMeter',
    ...G,
  },
  { key: 'rooms', label: 'تعداد خواب', kind: 'chips', options: [...ROOMS], ...C },
  {
    key: 'yearMin',
    label: 'حداقل سن بنا (سال)',
    kind: 'range',
    urlParam: 'year',
    ...G,
  },
  {
    key: 'yearMax',
    label: 'حداکثر سن بنا (سال)',
    kind: 'range',
    urlParam: 'year',
    ...G,
  },
  { key: 'floorMin', label: 'حداقل طبقه', kind: 'range', urlParam: 'floor', ...G },
  { key: 'floorMax', label: 'حداکثر طبقه', kind: 'range', urlParam: 'floor', ...G },
  {
    key: 'amenities',
    label: 'امکانات',
    kind: 'multi',
    options: [...AMENITIES],
    ...C,
  },
  {
    key: 'deedType',
    label: 'نوع سند',
    kind: 'chips',
    options: [...DEED_TYPE],
    browse: true,
    intake: true,
  },
  ...BUILT_PROPERTY_EXTRAS,
];

const RENT_BUILT_SPEC: CategoryFilterSpec = [
  { key: 'dealType', label: 'نوع معامله', kind: 'chips', options: [...DEAL_TYPE_PROPERTY], required: true, ...C },
  { key: 'deposit', label: 'ودیعه (تومان)', kind: 'range', browse: true, intake: true },
  { key: 'monthlyRent', label: 'اجاره ماهانه (تومان)', kind: 'range', browse: true, intake: true },
  { key: 'deedType', label: 'نوع سند', kind: 'chips', options: [...DEED_TYPE], browse: true, intake: true },
  {
    key: 'rahnAmount',
    label: 'مبلغ رهن (تومان)',
    kind: 'range',
    showIf: { field: 'dealType', in: ['rent_rahn_full', 'rent_rahn_ejare'] },
    browse: true,
    intake: true,
  },
  {
    key: 'areaMin',
    label: 'حداقل متراژ (متر)',
    kind: 'range',
    urlParam: 'area',
    ...G,
  },
  {
    key: 'areaMax',
    label: 'حداکثر متراژ (متر)',
    kind: 'range',
    urlParam: 'area',
    ...G,
  },
  { key: 'rooms', label: 'تعداد خواب', kind: 'chips', options: [...ROOMS], ...C },
  {
    key: 'yearMin',
    label: 'حداقل سن بنا (سال)',
    kind: 'range',
    urlParam: 'year',
    ...G,
  },
  {
    key: 'yearMax',
    label: 'حداکثر سن بنا (سال)',
    kind: 'range',
    urlParam: 'year',
    ...G,
  },
  { key: 'floorMin', label: 'حداقل طبقه', kind: 'range', urlParam: 'floor', ...G },
  { key: 'floorMax', label: 'حداکثر طبقه', kind: 'range', urlParam: 'floor', ...G },
  {
    key: 'amenities',
    label: 'امکانات',
    kind: 'multi',
    options: [...AMENITIES],
    ...C,
  },
  ...BUILT_PROPERTY_EXTRAS,
];

const SHORT_TERM_SPEC: CategoryFilterSpec = [
  { key: 'dealType', label: 'نوع معامله', kind: 'chips', options: [...DEAL_TYPE_PROPERTY], required: true, ...C },
  {
    key: 'guestCount',
    label: 'تعداد نفرات',
    kind: 'chips',
    options: [...GUEST_COUNT],
    required: true,
    ...G,
  },
  {
    key: 'nightlyRent',
    label: 'اجاره هر شب (تومان)',
    kind: 'range',
    browse: true,
    intake: true,
  },
  {
    key: 'areaMin',
    label: 'حداقل متراژ (متر)',
    kind: 'range',
    urlParam: 'area',
    ...G,
  },
  {
    key: 'areaMax',
    label: 'حداکثر متراژ (متر)',
    kind: 'range',
    urlParam: 'area',
    ...G,
  },
  { key: 'rooms', label: 'تعداد اتاق', kind: 'chips', options: [...ROOMS], ...G },
  {
    key: 'shortTermAmenities',
    label: 'امکانات اقامت',
    kind: 'multi',
    options: [...SHORT_TERM_AMENITIES],
    ...G,
  },
  {
    key: 'moveInWhen',
    label: 'زمان ورود',
    kind: 'chips',
    options: [...MOVE_IN_WHEN],
    browse: false,
    intake: true,
  },
];

const LAND_SALE_SPEC: CategoryFilterSpec = [
  { key: 'dealType', label: 'نوع معامله', kind: 'chips', options: [...DEAL_TYPE_PROPERTY], required: true, ...C },
  { key: 'budget', label: 'بودجه / قیمت (تومان)', kind: 'range', browse: true, intake: true },
  {
    key: 'areaMin',
    label: 'حداقل متراژ (متر)',
    kind: 'range',
    urlParam: 'area',
    ...G,
  },
  {
    key: 'areaMax',
    label: 'حداکثر متراژ (متر)',
    kind: 'range',
    urlParam: 'area',
    ...G,
  },
  {
    key: 'pricePerMeterMin',
    label: 'حداقل قیمت هر متر (تومان)',
    kind: 'range',
    urlParam: 'pricePerMeter',
    ...G,
  },
  {
    key: 'pricePerMeterMax',
    label: 'حداکثر قیمت هر متر (تومان)',
    kind: 'range',
    urlParam: 'pricePerMeter',
    ...G,
  },
  {
    key: 'landUse',
    label: 'کاربری زمین',
    kind: 'chips',
    options: [...LAND_USE],
    ...G,
  },
  {
    key: 'plotWidth',
    label: 'عرض بر (متر)',
    kind: 'text',
    placeholder: 'مثلاً ۱۲',
    browse: false,
    intake: true,
  },
  {
    key: 'deedType',
    label: 'نوع سند',
    kind: 'chips',
    options: [...DEED_TYPE],
    browse: true,
    intake: true,
  },
  {
    key: 'posterKind',
    label: 'آگهی‌دهنده',
    kind: 'chips',
    options: [...POSTER_KIND],
    browse: false,
    intake: true,
  },
];

const LAND_RENT_SPEC: CategoryFilterSpec = [
  { key: 'dealType', label: 'نوع معامله', kind: 'chips', options: [...DEAL_TYPE_PROPERTY], required: true, ...C },
  { key: 'deposit', label: 'ودیعه (تومان)', kind: 'range', browse: true, intake: true },
  { key: 'monthlyRent', label: 'اجاره ماهانه (تومان)', kind: 'range', browse: true, intake: true },
  {
    key: 'rahnAmount',
    label: 'مبلغ رهن (تومان)',
    kind: 'range',
    showIf: { field: 'dealType', in: ['rent_rahn_full', 'rent_rahn_ejare'] },
    browse: true,
    intake: true,
  },
  {
    key: 'areaMin',
    label: 'حداقل متراژ (متر)',
    kind: 'range',
    urlParam: 'area',
    ...G,
  },
  {
    key: 'areaMax',
    label: 'حداکثر متراژ (متر)',
    kind: 'range',
    urlParam: 'area',
    ...G,
  },
  {
    key: 'landUse',
    label: 'کاربری زمین',
    kind: 'chips',
    options: [...LAND_USE],
    ...G,
  },
  {
    key: 'plotWidth',
    label: 'عرض بر (متر)',
    kind: 'text',
    placeholder: 'مثلاً ۱۲',
    browse: false,
    intake: true,
  },
  {
    key: 'posterKind',
    label: 'آگهی‌دهنده',
    kind: 'chips',
    options: [...POSTER_KIND],
    browse: false,
    intake: true,
  },
];

/** Global browse controls for needs marketplace (`/n/`). */
export const GLOBAL_NEED_BROWSE_SPEC: CategoryFilterSpec = [
  { key: '_price', label: 'قیمت', kind: 'range', globalKey: 'price', browse: true, intake: false, audience: 'need' },
  { key: '_hasPhoto', label: 'عکس‌دار', kind: 'toggle', globalKey: 'hasPhoto', browse: true, intake: false, audience: 'need' },
  { key: '_sort', label: 'مرتب‌سازی', kind: 'select', globalKey: 'sort', browse: true, intake: false, audience: 'need' },
];

/** Global browse controls for business marketplace (`/b/`). */
export const GLOBAL_BUSINESS_BROWSE_SPEC: CategoryFilterSpec = [
  { key: '_verified', label: 'تأییدشده', kind: 'toggle', globalKey: 'verified', browse: true, intake: false, audience: 'business' },
  { key: '_sort', label: 'مرتب‌سازی', kind: 'select', globalKey: 'sort', browse: true, intake: false, audience: 'business' },
];

/** @deprecated Use GLOBAL_NEED_BROWSE_SPEC */
export const GLOBAL_BROWSE_SPEC = GLOBAL_NEED_BROWSE_SPEC;

/** Category-root filters shown only on business browse (not listing/need fields). */
export const BUSINESS_ROOT_SPECS: Record<string, CategoryFilterSpec> = {
  'real-estate': [
    {
      key: 'serviceKind',
      label: 'نوع فعالیت',
      kind: 'chips',
      options: [
        { value: 'agency', label: 'آژانس' },
        { value: 'partnership', label: 'مشارکت' },
        { value: 'presale', label: 'پیش‌فروش' },
      ],
      audience: 'business',
      browse: true,
      intake: false,
    },
  ],
  services: [
    {
      key: 'serviceCategory',
      label: 'حوزه فعالیت',
      kind: 'chips',
      options: [
        { value: 'repairs', label: 'تعمیرات' },
        { value: 'cleaning', label: 'نظافت' },
        { value: 'transport', label: 'حمل و نقل' },
        { value: 'plumbing', label: 'لوله‌کشی' },
        { value: 'moving', label: 'اسباب‌کشی' },
        { value: 'electrical', label: 'برق‌کاری' },
        { value: 'painting', label: 'نقاشی' },
        { value: 'medical', label: 'درمانی' },
        { value: 'legal', label: 'حقوقی' },
        { value: 'it', label: 'فناوری' },
        { value: 'other', label: 'سایر' },
      ],
      audience: 'business',
      browse: true,
      intake: false,
    },
  ],
};

export const ROOT_SPECS: Record<string, CategoryFilterSpec> = {
  'real-estate': [
    { key: 'dealType', label: 'نوع معامله', kind: 'chips', options: [...DEAL_TYPE_PROPERTY], required: true, ...G },
    {
      key: 'propertyKind',
      label: 'نوع ملک',
      kind: 'chips',
      options: [...PROPERTY_KIND],
      showIf: { field: 'dealType', in: ['buy', 'sell', 'rent_monthly', 'rent_rahn_full', 'rent_rahn_ejare'] },
      ...G,
    },
    { key: '_urgent', label: 'فوری', kind: 'toggle', globalKey: 'urgent', browse: true, intake: false },
    { key: '_recent', label: 'بازه زمانی', kind: 'select', globalKey: 'recent', browse: true, intake: false },
  ],
  vehicles: [
    { key: 'dealType', label: 'نوع معامله', kind: 'chips', options: [...DEAL_TYPE_VEHICLE], required: true, ...G },
    { key: 'vehicleKind', label: 'نوع وسیله', kind: 'chips', options: [...VEHICLE_KIND], showIf: { field: 'dealType', in: ['buy', 'sell', 'rent'] }, ...G },
    { key: 'condition', label: 'وضعیت', kind: 'chips', options: [...CONDITION], showIf: { field: 'dealType', in: ['buy', 'sell'] }, ...C },
    { key: 'yearMin', label: 'سال ساخت', kind: 'range', urlParam: 'year', showIf: { field: 'dealType', in: ['buy', 'rent'] }, ...C },
    { key: 'mileageMax', label: 'حداکثر کارکرد (کیلومتر)', kind: 'range', urlParam: 'mileage', showIf: { field: 'dealType', in: ['buy', 'sell'] }, ...C },
    { key: 'brand', label: 'برند / مدل', kind: 'text', placeholder: 'مثلاً پژو ۲۰۶', browse: false, intake: true, intakeTier: 'critical' },
    { key: 'budget', label: 'بودجه / قیمت', kind: 'range', showIf: { field: 'dealType', in: ['buy', 'sell', 'rent', 'parts'] }, browse: false, intake: true, intakeTier: 'critical' },
    { key: 'serviceType', label: 'شرح خدمات', kind: 'text', showIf: { field: 'dealType', equals: 'service' }, browse: false, intake: true },
    { key: '_recent', label: 'بازه زمانی', kind: 'select', globalKey: 'recent', browse: true, intake: false },
  ],
  electronics: [
    { key: 'dealType', label: 'خرید / فروش', kind: 'chips', options: [...DEAL_TYPE_PRODUCT], required: true, ...G },
    { key: 'productName', label: 'نام کالا', kind: 'text', required: true, browse: false, intake: true },
    { key: 'condition', label: 'وضعیت', kind: 'chips', options: [...CONDITION], ...C },
    { key: 'budget', label: 'بودجه / قیمت', kind: 'range', browse: false, intake: true, intakeTier: 'critical' },
    { key: 'storage', label: 'حافظه', kind: 'chips', options: [...STORAGE_MOBILE], browse: true, intake: true, intakeTier: 'critical' },
    { key: 'ram', label: 'رم', kind: 'chips', options: [...RAM_OPTIONS], browse: true, intake: true },
    { key: '_urgent', label: 'فوری', kind: 'toggle', globalKey: 'urgent', browse: true, intake: false },
    { key: '_recent', label: 'بازه زمانی', kind: 'select', globalKey: 'recent', browse: true, intake: false },
  ],
  'home-appliances': [
    { key: 'dealType', label: 'خرید / فروش', kind: 'chips', options: [...DEAL_TYPE_PRODUCT], ...G },
    { key: 'productName', label: 'نام کالا', kind: 'text', browse: false, intake: true },
    { key: 'brand', label: 'برند', kind: 'text', browse: false, intake: true, intakeTier: 'critical' },
    { key: 'condition', label: 'وضعیت', kind: 'chips', options: [...CONDITION], ...C },
    { key: 'budget', label: 'بودجه / قیمت', kind: 'range', browse: false, intake: true, intakeTier: 'critical' },
    { key: '_recent', label: 'بازه زمانی', kind: 'select', globalKey: 'recent', browse: true, intake: false },
  ],
  services: [
    { key: 'serviceCategory', label: 'دسته خدمات', kind: 'chips', options: [
      { value: 'repairs', label: 'تعمیرات' },
      { value: 'cleaning', label: 'نظافت' },
      { value: 'transport', label: 'حمل و نقل' },
      { value: 'plumbing', label: 'لوله‌کشی' },
      { value: 'moving', label: 'اسباب‌کشی' },
      { value: 'electrical', label: 'برق‌کاری' },
      { value: 'painting', label: 'نقاشی' },
      { value: 'medical', label: 'درمانی' },
      { value: 'legal', label: 'حقوقی' },
      { value: 'it', label: 'فناوری' },
      { value: 'other', label: 'سایر' },
    ], required: true, browse: false, intake: true },
    { key: 'serviceType', label: 'شرح خدمت', kind: 'text', required: true, browse: false, intake: true, intakeTier: 'critical' },
    { key: 'when', label: 'زمان', kind: 'chips', options: [...SERVICE_WHEN], ...C },
    { key: 'budget', label: 'بودجه تقریبی', kind: 'range', browse: false, intake: true, intakeTier: 'critical' },
    { key: '_urgent', label: 'فوری', kind: 'toggle', globalKey: 'urgent', browse: true, intake: false },
    { key: '_recent', label: 'بازه زمانی', kind: 'select', globalKey: 'recent', browse: true, intake: false },
  ],
  jobs: [
    { key: 'roleType', label: 'نوع آگهی', kind: 'chips', options: [...ROLE_TYPE], required: true, ...G },
    { key: 'jobTitle', label: 'عنوان شغل', kind: 'text', required: true, browse: false, intake: true },
    { key: 'employmentType', label: 'نوع همکاری', kind: 'chips', options: [...EMPLOYMENT_TYPE], ...C },
    { key: 'salaryMin', label: 'حقوق', kind: 'range', urlParam: 'salary', showIf: { field: 'roleType', equals: 'hiring' }, ...C },
    { key: 'experience', label: 'سابقه', kind: 'chips', options: [...EXPERIENCE], showIf: { field: 'roleType', equals: 'seeking' }, ...C },
    { key: '_recent', label: 'بازه زمانی', kind: 'select', globalKey: 'recent', browse: true, intake: false },
  ],
  social: [
    { key: 'socialType', label: 'نوع', kind: 'chips', options: [...SOCIAL_TYPE], ...G },
    { key: '_urgent', label: 'فوری', kind: 'toggle', globalKey: 'urgent', browse: true, intake: false },
    { key: '_recent', label: 'بازه زمانی', kind: 'select', globalKey: 'recent', browse: true, intake: false },
  ],
  'personal-items': [
    { key: 'dealType', label: 'خرید / فروش', kind: 'chips', options: [...DEAL_TYPE_PRODUCT], ...G },
    { key: 'productName', label: 'نام کالا', kind: 'text', browse: false, intake: true },
    { key: 'brand', label: 'برند', kind: 'text', placeholder: 'مثلاً نایک، آدیداس', browse: false, intake: true },
    { key: 'condition', label: 'وضعیت', kind: 'chips', options: [...CONDITION], ...G },
    { key: 'budget', label: 'بودجه / قیمت', kind: 'range', browse: false, intake: true },
    { key: '_recent', label: 'بازه زمانی', kind: 'select', globalKey: 'recent', browse: true, intake: false },
  ],
  entertainment: [
    { key: 'dealType', label: 'خرید / فروش', kind: 'chips', options: [...DEAL_TYPE_PRODUCT], ...G },
    { key: 'productName', label: 'نام کالا', kind: 'text', browse: false, intake: true },
    { key: 'brand', label: 'برند', kind: 'text', placeholder: 'مثلاً یاماها، رولند', browse: false, intake: true },
    { key: 'condition', label: 'وضعیت', kind: 'chips', options: [...CONDITION], ...G },
    { key: 'budget', label: 'بودجه / قیمت', kind: 'range', browse: false, intake: true },
    { key: '_recent', label: 'بازه زمانی', kind: 'select', globalKey: 'recent', browse: true, intake: false },
  ],
};

export const PARENT_SPECS: Record<string, CategoryFilterSpec> = {
  'mobile-tablet': [
    { key: 'storage', label: 'حافظه', kind: 'chips', options: [...STORAGE_MOBILE], browse: true, intake: true },
  ],
  'mobile-phone': [
    { key: 'storage', label: 'حافظه', kind: 'chips', options: [...STORAGE_MOBILE], browse: true, intake: true },
  ],
  computer: [
    { key: 'ram', label: 'رم', kind: 'chips', options: [...RAM_OPTIONS], browse: true, intake: true },
    { key: 'storage', label: 'حافظه', kind: 'chips', options: [...STORAGE_MOBILE], browse: true, intake: true },
  ],
  laptop: [
    { key: 'ram', label: 'رم', kind: 'chips', options: [...RAM_OPTIONS], browse: true, intake: true },
  ],
  'desktop-computer': [
    { key: 'ram', label: 'رم', kind: 'chips', options: [...RAM_OPTIONS], browse: true, intake: true },
  ],
  'real-estate-services': [
    { key: 'serviceKind', label: 'نوع خدمات', kind: 'chips', options: [
      { value: 'agency', label: 'آژانس' },
      { value: 'partnership', label: 'مشارکت' },
      { value: 'presale', label: 'پیش‌فروش' },
    ], browse: true, intake: true },
  ],
  'pre-sale-services': [
    { key: 'dealType', label: 'نوع درخواست', kind: 'chips', options: [
      { value: 'buy', label: 'خرید واحد' },
      { value: 'sell', label: 'فروش / واگذاری' },
      { value: 'consult', label: 'مشاوره' },
    ], required: true, browse: true, intake: true },
    { key: 'projectName', label: 'نام پروژه', kind: 'text', browse: false, intake: true },
    { key: 'delivery', label: 'زمان تحویل', kind: 'chips', options: [...DELIVERY_PRE_SALE], browse: true, intake: true },
    { key: 'propertyKind', label: 'نوع پروژه', kind: 'chips', options: [
      { value: 'apartment', label: 'آپارتمان' },
      { value: 'villa', label: 'ویلایی' },
      { value: 'commercial', label: 'تجاری' },
    ], browse: true, intake: true },
  ],
  'short-term-rent': [...SHORT_TERM_SPEC],
  pets: [
    { key: 'petType', label: 'نوع حیوان', kind: 'chips', options: [...PET_TYPE], browse: true, intake: true },
  ],
  'musical-instruments': [
    { key: 'brand', label: 'برند', kind: 'text', placeholder: 'مثلاً یاماها، رولند', browse: false, intake: true },
  ],
  'game-console': [
    { key: 'brand', label: 'برند / مدل', kind: 'text', placeholder: 'مثلاً پلی‌استیشن ۵', browse: false, intake: true },
  ],
  motorcycle: [
    { key: 'brand', label: 'برند / مدل', kind: 'text', placeholder: 'مثلاً هوندا سی‌بی‌آر', browse: false, intake: true },
  ],
  'kitchen-appliances': [
    { key: 'brand', label: 'برند', kind: 'text', browse: false, intake: true },
  ],
  repairs: [
    {
      key: 'serviceType',
      label: 'شرح خدمت',
      kind: 'text',
      placeholder: 'مثلاً: برند، مدل، علت خرابی',
      required: true,
      browse: false,
      intake: true,
    },
    { key: 'when', label: 'زمان', kind: 'chips', options: [...SERVICE_WHEN], ...G },
    { key: 'budget', label: 'بودجه تقریبی', kind: 'range', browse: false, intake: true },
  ],
};

export const LEAF_SPECS: Record<string, CategoryFilterSpec> = {
  'land-sale': [
    ...LAND_SALE_SPEC,
    { key: 'rooms', label: 'تعداد خواب', kind: 'chips', options: [...ROOMS], browse: false, intake: false },
    { key: 'amenities', label: 'امکانات', kind: 'multi', options: [...AMENITIES], browse: false, intake: false },
    { key: 'yearMin', label: 'حداقل سن بنا', kind: 'range', urlParam: 'year', browse: false, intake: false },
    { key: 'yearMax', label: 'حداکثر سن بنا', kind: 'range', urlParam: 'year', browse: false, intake: false },
    { key: 'floorMin', label: 'طبقه', kind: 'range', browse: false, intake: false },
    { key: 'floorMax', label: 'طبقه', kind: 'range', browse: false, intake: false },
    { key: 'deedType', label: 'سند', kind: 'chips', options: [...DEED_TYPE], browse: false, intake: false },
  ],
  'land-rent': [
    ...LAND_RENT_SPEC,
    { key: 'rooms', label: 'تعداد خواب', kind: 'chips', options: [...ROOMS], browse: false, intake: false },
    { key: 'amenities', label: 'امکانات', kind: 'multi', options: [...AMENITIES], browse: false, intake: false },
    { key: 'yearMin', label: 'حداقل سن بنا', kind: 'range', urlParam: 'year', browse: false, intake: false },
    { key: 'yearMax', label: 'حداکثر سن بنا', kind: 'range', urlParam: 'year', browse: false, intake: false },
    { key: 'familyCount', label: 'تعداد نفرات', kind: 'chips', options: [...FAMILY_COUNT], browse: false, intake: false },
  ],
  'apartment-sale': [...SALE_RESIDENTIAL_SPEC],
  'villa-sale': [...SALE_RESIDENTIAL_SPEC],
  'office-sale': [...SALE_RESIDENTIAL_SPEC],
  'shop-sale': [...SALE_RESIDENTIAL_SPEC],
  'industrial-sale': [
    { key: 'budget', label: 'بودجه / قیمت', kind: 'range', browse: true, intake: true },
    { key: 'areaMin', label: 'حداقل متراژ', kind: 'range', urlParam: 'area', ...G },
    { key: 'areaMax', label: 'حداکثر متراژ', kind: 'range', urlParam: 'area', ...G },
    { key: 'pricePerMeterMin', label: 'حداقل قیمت هر متر', kind: 'range', urlParam: 'pricePerMeter', ...G },
    { key: 'pricePerMeterMax', label: 'حداکثر قیمت هر متر', kind: 'range', urlParam: 'pricePerMeter', ...G },
    { key: 'deedType', label: 'نوع سند', kind: 'chips', options: [...DEED_TYPE], browse: true, intake: true },
  ],
  'apartment-rent': [...RENT_BUILT_SPEC, { key: 'familyCount', label: 'تعداد نفرات خانواده', kind: 'chips', options: [...FAMILY_COUNT], ...G }],
  'villa-rent': [...RENT_BUILT_SPEC, { key: 'familyCount', label: 'تعداد نفرات خانواده', kind: 'chips', options: [...FAMILY_COUNT], ...G }],
  'office-rent': [...RENT_BUILT_SPEC],
  'shop-rent': [...RENT_BUILT_SPEC],
  'industrial-rent': [...RENT_BUILT_SPEC],
  'suite-apartment-rent': [...SHORT_TERM_SPEC],
  'villa-short-rent': [...SHORT_TERM_SPEC],
  'workspace-short-rent': [
    ...SHORT_TERM_SPEC,
    { key: 'rooms', label: 'تعداد اتاق', kind: 'chips', options: [...ROOMS], browse: false, intake: false },
  ],
  'construction-partnership': [
    {
      key: 'propertyKind',
      label: 'نوع ملک / زمین',
      kind: 'chips',
      options: [...PROPERTY_KIND],
      browse: true,
      intake: true,
    },
    {
      key: 'areaMin',
      label: 'متراژ زمین (متر)',
      kind: 'range',
      urlParam: 'area',
      browse: true,
      intake: true,
    },
    {
      key: 'plotWidth',
      label: 'عرض زمین (متر)',
      kind: 'text',
      placeholder: 'مثلاً ۱۲',
      browse: false,
      intake: true,
    },
  ],
  plumbing: [
    {
      key: 'serviceType',
      label: 'شرح خدمت',
      kind: 'text',
      placeholder: 'مثلاً لوله\u200cکشی، رفع نشتی',
      required: true,
      browse: false,
      intake: true,
    },
  ],
  electrical: [
    {
      key: 'serviceType',
      label: 'شرح خدمت',
      kind: 'text',
      placeholder: 'مثلاً سیم\u200cکشی، تعمیر تابلو',
      required: true,
      browse: false,
      intake: true,
    },
  ],
  cleaning: [
    {
      key: 'serviceType',
      label: 'شرح خدمت',
      kind: 'text',
      placeholder: 'مثلاً نظافت منزل، شستشوی نما',
      required: true,
      browse: false,
      intake: true,
    },
  ],
  moving: [
    {
      key: 'serviceType',
      label: 'شرح خدمت',
      kind: 'text',
      placeholder: 'مثلاً اسباب\u200cکشی دربست',
      required: true,
      browse: false,
      intake: true,
    },
  ],
  painting: [
    {
      key: 'serviceType',
      label: 'شرح خدمت',
      kind: 'text',
      placeholder: 'مثلاً نقاشی ساختمان',
      required: true,
      browse: false,
      intake: true,
    },
  ],
  it: [
    {
      key: 'employmentType',
      label: 'نوع همکاری',
      kind: 'chips',
      options: [...EMPLOYMENT_TYPE],
      browse: true,
      intake: true,
    },
    {
      key: 'experience',
      label: 'سابقه',
      kind: 'chips',
      options: [...EXPERIENCE],
      showIf: { field: 'roleType', equals: 'seeking' },
      browse: true,
      intake: true,
    },
  ],
  car: [
    {
      key: 'brand',
      label: 'برند / مدل',
      kind: 'text',
      placeholder: 'مثلاً پژو ۲۰۶، دنا پلاس',
      required: true,
      browse: false,
      intake: true,
    },
    {
      key: 'mileageMax',
      label: 'حداکثر کارکرد (کیلومتر)',
      kind: 'range',
      urlParam: 'mileage',
      showIf: { field: 'dealType', in: ['buy', 'sell'] },
      browse: true,
      intake: true,
    },
    {
      key: 'yearMin',
      label: 'سال ساخت',
      kind: 'range',
      urlParam: 'year',
      showIf: { field: 'dealType', in: ['buy', 'rent'] },
      browse: true,
      intake: true,
    },
  ],
  'spare-parts': [
    { key: 'yearMin', label: 'سال ساخت', kind: 'range', urlParam: 'year', browse: false, intake: false },
    { key: 'mileageMax', label: 'کارکرد', kind: 'range', urlParam: 'mileage', browse: false, intake: false },
    { key: 'vehicleKind', label: 'نوع وسیله', kind: 'chips', options: [...VEHICLE_KIND], browse: false, intake: false },
  ],
  boat: [
    { key: 'vehicleKind', label: 'نوع وسیله', kind: 'chips', options: [...VEHICLE_KIND], browse: false, intake: false },
  ],
};

/** Intake-only tail fields appended to every vertical schema. */
export const INTAKE_TAIL: CategoryFilterSpec = [
  { key: 'location', label: 'شهر و محله', kind: 'text', placeholder: 'مثلاً تهران، ولنجک', browse: false, intake: true },
  { key: 'details', label: 'توضیحات تکمیلی', kind: 'text', placeholder: 'جزئیات بیشتر…', browse: false, intake: true },
];

/** @deprecated Use GLOBAL_BUSINESS_BROWSE_SPEC */
export const BUSINESS_BROWSE_SPEC = GLOBAL_BUSINESS_BROWSE_SPEC;
