/**
 * Default business occupation registry (seed / fallback).
 * Runtime source: src/data/business-occupations.json via occupations-registry.
 */
import type { BusinessOccupation } from './business-occupation-types';

export const DEFAULT_BUSINESS_OCCUPATIONS: readonly BusinessOccupation[] = [
  // ── real-estate-facility
  { slug: 'real-estate-facility', parentSlug: null, title: 'املاک و ساختمان', englishTitle: 'Real Estate', depth: 0, sortOrder: 100 },
  { slug: 'real-estate-agent', parentSlug: 'real-estate-facility', title: 'مشاور املاک', englishTitle: 'Real Estate Agent', depth: 1, sortOrder: 101 },
  { slug: 'interior-designer', parentSlug: 'real-estate-facility', title: 'طراحی داخلی و دکوراسیون', englishTitle: 'Interior Designer', depth: 1, sortOrder: 102 },
  { slug: 'architect', parentSlug: 'real-estate-facility', title: 'معمار', englishTitle: 'Architect', depth: 1, sortOrder: 103 },
  { slug: 'property-manager', parentSlug: 'real-estate-facility', title: 'مدیریت ساختمان و مجتمع', englishTitle: 'Property Manager', depth: 1, sortOrder: 104 },
  { slug: 'facility-maintenance', parentSlug: 'real-estate-facility', title: 'نگهداری و تعمیرات ساختمان', englishTitle: 'Facility Maintenance', depth: 1, sortOrder: 105 },
  { slug: 'elevator-technician', parentSlug: 'real-estate-facility', title: 'تعمیر و نگهداری آسانسور', englishTitle: 'Elevator Technician', depth: 1, sortOrder: 106 },
  { slug: 'land-surveyor', parentSlug: 'real-estate-facility', title: 'کارشناس نقشه‌برداری و ملک', englishTitle: 'Land Surveyor', depth: 1, sortOrder: 107 },
  { slug: 'official-appraiser', parentSlug: 'real-estate-facility', title: 'کارشناس رسمی و قیمت‌گذاری', englishTitle: 'Official Appraiser', depth: 1, sortOrder: 108 },
  { slug: 'gate-automation', parentSlug: 'real-estate-facility', title: 'درب اتوماتیک و شیشه‌ای', englishTitle: 'Gate Automation', depth: 1, sortOrder: 109 },

  // ── home-personal-services
  { slug: 'home-personal-services', parentSlug: null, title: 'خدمات منزل و شخصی', englishTitle: 'Home Services', depth: 0, sortOrder: 200 },
  { slug: 'cleaner', parentSlug: 'home-personal-services', title: 'نظافت منزل و محل کار', englishTitle: 'Cleaner', depth: 1, sortOrder: 201 },
  { slug: 'moving-company', parentSlug: 'home-personal-services', title: 'اسباب‌کشی و باربری', englishTitle: 'Moving', depth: 1, sortOrder: 202 },
  { slug: 'appliance-repair', parentSlug: 'home-personal-services', title: 'تعمیر لوازم خانگی', englishTitle: 'Appliance Repair', depth: 1, sortOrder: 203 },
  { slug: 'locksmith', parentSlug: 'home-personal-services', title: 'قفل‌سازی و کلیدسازی', englishTitle: 'Locksmith', depth: 1, sortOrder: 204 },
  { slug: 'gardener-landscaping', parentSlug: 'home-personal-services', title: 'باغبانی و فضای سبز', englishTitle: 'Landscaping', depth: 1, sortOrder: 205 },
  { slug: 'pest-control', parentSlug: 'home-personal-services', title: 'سم‌پاشی و ضدعفونی', englishTitle: 'Pest Control', depth: 1, sortOrder: 206 },
  { slug: 'laundry-dry-clean', parentSlug: 'home-personal-services', title: 'خشکشویی و لباسشویی', englishTitle: 'Laundry', depth: 1, sortOrder: 207 },
  { slug: 'carpet-cleaning', parentSlug: 'home-personal-services', title: 'قالیشویی و شستشوی فرش', englishTitle: 'Carpet Cleaning', depth: 1, sortOrder: 208 },
  { slug: 'upholstery-furniture', parentSlug: 'home-personal-services', title: 'تعمیر و رویه‌کوبی مبلمان', englishTitle: 'Upholstery', depth: 1, sortOrder: 209 },
  { slug: 'curtain-blinds', parentSlug: 'home-personal-services', title: 'پرده و کرکره', englishTitle: 'Curtains & Blinds', depth: 1, sortOrder: 210 },
  { slug: 'water-tank-cleaning', parentSlug: 'home-personal-services', title: 'شستشوی مخزن و لوله‌کشی آب', englishTitle: 'Water Tank Cleaning', depth: 1, sortOrder: 211 },
  { slug: 'pool-maintenance', parentSlug: 'home-personal-services', title: 'نگهداری استخر', englishTitle: 'Pool Maintenance', depth: 1, sortOrder: 212 },
  { slug: 'elderly-home-care', parentSlug: 'home-personal-services', title: 'مراقبت و پرستاری در منزل', englishTitle: 'Home Care', depth: 1, sortOrder: 213 },
  { slug: 'nanny-childcare', parentSlug: 'home-personal-services', title: 'پرستار کودک و بیبی‌سیتر', englishTitle: 'Childcare', depth: 1, sortOrder: 214 },

  // ── trades-construction
  { slug: 'trades-construction', parentSlug: null, title: 'ساختمان و تأسیسات', englishTitle: 'Trades & Construction', depth: 0, sortOrder: 300 },
  { slug: 'plumber', parentSlug: 'trades-construction', title: 'لوله‌کش', englishTitle: 'Plumber', depth: 1, sortOrder: 301 },
  { slug: 'electrician', parentSlug: 'trades-construction', title: 'برق‌کار', englishTitle: 'Electrician', depth: 1, sortOrder: 302 },
  { slug: 'hvac-technician', parentSlug: 'trades-construction', title: 'تأسیسات گرمایش و سرمایش', englishTitle: 'HVAC', depth: 1, sortOrder: 303 },
  { slug: 'painter-decorator', parentSlug: 'trades-construction', title: 'نقاش ساختمان', englishTitle: 'Painter', depth: 1, sortOrder: 304 },
  { slug: 'tiler', parentSlug: 'trades-construction', title: 'کاشی‌کار و سرامیک', englishTitle: 'Tiler', depth: 1, sortOrder: 305 },
  { slug: 'carpenter', parentSlug: 'trades-construction', title: 'نجاری و کابینت‌سازی', englishTitle: 'Carpenter', depth: 1, sortOrder: 306 },
  { slug: 'general-contractor', parentSlug: 'trades-construction', title: 'پیمانکار ساختمان', englishTitle: 'General Contractor', depth: 1, sortOrder: 307 },
  { slug: 'mason', parentSlug: 'trades-construction', title: 'گچ‌کار و بنّا', englishTitle: 'Mason', depth: 1, sortOrder: 308 },
  { slug: 'welder-metalwork', parentSlug: 'trades-construction', title: 'جوشکاری و آهنگری', englishTitle: 'Welder', depth: 1, sortOrder: 309 },
  { slug: 'glazier', parentSlug: 'trades-construction', title: 'شیشه‌بر و نصب شیشه', englishTitle: 'Glazier', depth: 1, sortOrder: 310 },
  { slug: 'roofer', parentSlug: 'trades-construction', title: 'سقف‌سازی و عایق‌کاری', englishTitle: 'Roofer', depth: 1, sortOrder: 311 },
  { slug: 'aluminum-windows', parentSlug: 'trades-construction', title: 'آلومینیوم و درب و پنجره', englishTitle: 'Windows & Doors', depth: 1, sortOrder: 312 },
  { slug: 'parquet-flooring', parentSlug: 'trades-construction', title: 'پارکت و کف‌پوش', englishTitle: 'Flooring', depth: 1, sortOrder: 313 },
  { slug: 'stone-marble', parentSlug: 'trades-construction', title: 'سنگ‌کار و مرمر', englishTitle: 'Stone & Marble', depth: 1, sortOrder: 314 },
  { slug: 'demolition-excavation', parentSlug: 'trades-construction', title: 'تخریب و گودبرداری', englishTitle: 'Demolition', depth: 1, sortOrder: 315 },
  { slug: 'scaffolding', parentSlug: 'trades-construction', title: 'داربست و سازه موقت', englishTitle: 'Scaffolding', depth: 1, sortOrder: 316 },
  { slug: 'solar-panel-installer', parentSlug: 'trades-construction', title: 'نصب پنل خورشیدی', englishTitle: 'Solar Installer', depth: 1, sortOrder: 317 },
  { slug: 'waterproofing', parentSlug: 'trades-construction', title: 'ایزوگام و آب‌بندی', englishTitle: 'Waterproofing', depth: 1, sortOrder: 318 },
  { slug: 'kitchen-countertop', parentSlug: 'trades-construction', title: 'صفحه‌کابینت و کانتر', englishTitle: 'Countertops', depth: 1, sortOrder: 319 },
  { slug: 'steel-structure', parentSlug: 'trades-construction', title: 'سازه فلزی و جوش ساختمان', englishTitle: 'Steel Structure', depth: 1, sortOrder: 320 },
  { slug: 'building-materials-supplier', parentSlug: 'trades-construction', title: 'مصالح ساختمانی', englishTitle: 'Building Materials', depth: 1, sortOrder: 321 },
  { slug: 'hardware-tools-store', parentSlug: 'trades-construction', title: 'ابزارآلات و یراق‌آلات', englishTitle: 'Hardware Store', depth: 1, sortOrder: 322 },
  { slug: 'plasterboard-drywall', parentSlug: 'trades-construction', title: 'گچ‌بری و دیوار خشک', englishTitle: 'Drywall', depth: 1, sortOrder: 323 },

  // ── tech-digital
  { slug: 'tech-digital', parentSlug: null, title: 'فناوری و دیجیتال', englishTitle: 'Tech & Digital', depth: 0, sortOrder: 400 },
  { slug: 'web-developer', parentSlug: 'tech-digital', title: 'برنامه‌نویس وب و اپلیکیشن', englishTitle: 'Web Developer', depth: 1, sortOrder: 401 },
  { slug: 'graphic-designer', parentSlug: 'tech-digital', title: 'طراح گرافیک', englishTitle: 'Graphic Designer', depth: 1, sortOrder: 402 },
  { slug: 'seo-digital-marketing', parentSlug: 'tech-digital', title: 'سئو و بازاریابی دیجیتال', englishTitle: 'Digital Marketing', depth: 1, sortOrder: 403 },
  { slug: 'mobile-repair', parentSlug: 'tech-digital', title: 'تعمیر موبایل و تبلت', englishTitle: 'Mobile Repair', depth: 1, sortOrder: 404 },
  { slug: 'computer-repair', parentSlug: 'tech-digital', title: 'تعمیر رایانه و لپ‌تاپ', englishTitle: 'Computer Repair', depth: 1, sortOrder: 405 },
  { slug: 'it-support', parentSlug: 'tech-digital', title: 'پشتیبانی شبکه و IT', englishTitle: 'IT Support', depth: 1, sortOrder: 406 },
  { slug: 'ui-ux-designer', parentSlug: 'tech-digital', title: 'طراح UI/UX', englishTitle: 'UI/UX Designer', depth: 1, sortOrder: 407 },
  { slug: 'cctv-security-systems', parentSlug: 'tech-digital', title: 'دوربین مداربسته و امنیت', englishTitle: 'CCTV & Security', depth: 1, sortOrder: 408 },
  { slug: 'social-media-manager', parentSlug: 'tech-digital', title: 'مدیریت شبکه‌های اجتماعی', englishTitle: 'Social Media Manager', depth: 1, sortOrder: 409 },
  { slug: 'printing-copy-center', parentSlug: 'tech-digital', title: 'چاپ و تکثیر', englishTitle: 'Print Shop', depth: 1, sortOrder: 410 },
  { slug: 'mobile-phone-store', parentSlug: 'tech-digital', title: 'فروشگاه موبایل و تبلت', englishTitle: 'Mobile Phone Store', depth: 1, sortOrder: 411 },
  { slug: 'computer-store', parentSlug: 'tech-digital', title: 'فروشگاه رایانه و لپ‌تاپ', englishTitle: 'Computer Store', depth: 1, sortOrder: 412 },
  { slug: 'electronics-store', parentSlug: 'tech-digital', title: 'فروشگاه لوازم الکترونیک', englishTitle: 'Electronics Store', depth: 1, sortOrder: 413 },

  // ── transport-logistics
  { slug: 'transport-logistics', parentSlug: null, title: 'حمل‌ونقل و خودرو', englishTitle: 'Transport & Auto', depth: 0, sortOrder: 500 },
  { slug: 'auto-mechanic', parentSlug: 'transport-logistics', title: 'مکانیک خودرو', englishTitle: 'Auto Mechanic', depth: 1, sortOrder: 501 },
  { slug: 'auto-body-paint', parentSlug: 'transport-logistics', title: 'صافکاری و نقاشی خودرو', englishTitle: 'Auto Body', depth: 1, sortOrder: 502 },
  { slug: 'auto-electric', parentSlug: 'transport-logistics', title: 'برق‌کار خودرو', englishTitle: 'Auto Electrician', depth: 1, sortOrder: 503 },
  { slug: 'tire-wheel-service', parentSlug: 'transport-logistics', title: 'لاستیک‌فروشی و آپاراتی', englishTitle: 'Tire Service', depth: 1, sortOrder: 504 },
  { slug: 'car-wash-detailing', parentSlug: 'transport-logistics', title: 'کارواش و دیتیلینگ', englishTitle: 'Car Wash', depth: 1, sortOrder: 505 },
  { slug: 'motorcycle-mechanic', parentSlug: 'transport-logistics', title: 'مکانیک موتورسیکلت', englishTitle: 'Motorcycle Mechanic', depth: 1, sortOrder: 506 },
  { slug: 'towing-roadside', parentSlug: 'transport-logistics', title: 'یدک‌کش و امداد جاده‌ای', englishTitle: 'Towing', depth: 1, sortOrder: 507 },
  { slug: 'courier-delivery', parentSlug: 'transport-logistics', title: 'پیک و ارسال', englishTitle: 'Courier', depth: 1, sortOrder: 508 },
  { slug: 'freight-trucking', parentSlug: 'transport-logistics', title: 'باربری و حمل بار سنگین', englishTitle: 'Freight', depth: 1, sortOrder: 509 },
  { slug: 'driver-taxi', parentSlug: 'transport-logistics', title: 'راننده تاکسی و اینترنتی', englishTitle: 'Driver', depth: 1, sortOrder: 510 },
  { slug: 'driving-instructor', parentSlug: 'transport-logistics', title: 'آموزش رانندگی', englishTitle: 'Driving Instructor', depth: 1, sortOrder: 511 },
  { slug: 'car-dealership', parentSlug: 'transport-logistics', title: 'نمایشگاه و فروش خودرو', englishTitle: 'Car Dealership', depth: 1, sortOrder: 512 },
  { slug: 'motorcycle-dealership', parentSlug: 'transport-logistics', title: 'نمایشگاه و فروش موتورسیکلت', englishTitle: 'Motorcycle Dealership', depth: 1, sortOrder: 513 },
  { slug: 'auto-parts-store', parentSlug: 'transport-logistics', title: 'فروشگاه لوازم یدکی خودرو', englishTitle: 'Auto Parts Store', depth: 1, sortOrder: 514 },
  { slug: 'car-rental-agency', parentSlug: 'transport-logistics', title: 'اجاره خودرو (آژانس)', englishTitle: 'Car Rental Agency', depth: 1, sortOrder: 515 },
  { slug: 'auto-glass', parentSlug: 'transport-logistics', title: 'شیشه و گلس بلور خودرو', englishTitle: 'Auto Glass', depth: 1, sortOrder: 516 },
  { slug: 'auto-upholstery', parentSlug: 'transport-logistics', title: 'داخل‌دوزی و صندلی خودرو', englishTitle: 'Auto Upholstery', depth: 1, sortOrder: 517 },
  { slug: 'auto-accessories-shop', parentSlug: 'transport-logistics', title: 'لوازم جانبی و صوتی خودرو', englishTitle: 'Auto Accessories', depth: 1, sortOrder: 518 },
  { slug: 'diesel-mechanic', parentSlug: 'transport-logistics', title: 'مکانیک خودرو سنگین و دیزل', englishTitle: 'Diesel Mechanic', depth: 1, sortOrder: 519 },
  { slug: 'crane-heavy-machinery', parentSlug: 'transport-logistics', title: 'جرثقیل و ماشین‌آلات سنگین', englishTitle: 'Crane & Heavy Machinery', depth: 1, sortOrder: 520 },

  // ── professional-legal-finance
  { slug: 'professional-legal-finance', parentSlug: null, title: 'حقوقی، مالی و مشاوره', englishTitle: 'Professional Services', depth: 0, sortOrder: 600 },
  { slug: 'lawyer', parentSlug: 'professional-legal-finance', title: 'وکیل و مشاور حقوقی', englishTitle: 'Lawyer', depth: 1, sortOrder: 601 },
  { slug: 'accountant', parentSlug: 'professional-legal-finance', title: 'حسابدار و حسابرسی', englishTitle: 'Accountant', depth: 1, sortOrder: 602 },
  { slug: 'tax-advisor', parentSlug: 'professional-legal-finance', title: 'مشاور مالیاتی', englishTitle: 'Tax Advisor', depth: 1, sortOrder: 603 },
  { slug: 'insurance-agent', parentSlug: 'professional-legal-finance', title: 'نماینده بیمه', englishTitle: 'Insurance Agent', depth: 1, sortOrder: 604 },
  { slug: 'financial-advisor', parentSlug: 'professional-legal-finance', title: 'مشاور سرمایه‌گذاری و مالی', englishTitle: 'Financial Advisor', depth: 1, sortOrder: 605 },
  { slug: 'notary-legal-docs', parentSlug: 'professional-legal-finance', title: 'خدمات ثبت، اسناد و دفترخانه', englishTitle: 'Notary & Registry', depth: 1, sortOrder: 606 },
  { slug: 'recruitment-hr', parentSlug: 'professional-legal-finance', title: 'کاریابی و منابع انسانی', englishTitle: 'Recruitment', depth: 1, sortOrder: 607 },
  { slug: 'management-consultant', parentSlug: 'professional-legal-finance', title: 'مشاور مدیریت و سازمان', englishTitle: 'Management Consultant', depth: 1, sortOrder: 608 },
  { slug: 'customs-broker', parentSlug: 'professional-legal-finance', title: 'ترخیص‌کار گمرک', englishTitle: 'Customs Broker', depth: 1, sortOrder: 609 },
  { slug: 'import-export-trader', parentSlug: 'professional-legal-finance', title: 'بازرگانی و واردات صادرات', englishTitle: 'Import Export', depth: 1, sortOrder: 610 },

  // ── health-beauty
  { slug: 'health-beauty', parentSlug: null, title: 'سلامت، درمان و زیبایی', englishTitle: 'Health & Beauty', depth: 0, sortOrder: 700 },
  { slug: 'dentist', parentSlug: 'health-beauty', title: 'دندانپزشک', englishTitle: 'Dentist', depth: 1, sortOrder: 701 },
  { slug: 'general-practitioner', parentSlug: 'health-beauty', title: 'پزشک عمومی / مطب', englishTitle: 'GP', depth: 1, sortOrder: 702 },
  { slug: 'pharmacy', parentSlug: 'health-beauty', title: 'داروخانه', englishTitle: 'Pharmacy', depth: 1, sortOrder: 703 },
  { slug: 'medical-lab', parentSlug: 'health-beauty', title: 'آزمایشگاه پزشکی', englishTitle: 'Medical Lab', depth: 1, sortOrder: 704 },
  { slug: 'veterinarian', parentSlug: 'health-beauty', title: 'دامپزشک', englishTitle: 'Veterinarian', depth: 1, sortOrder: 705 },
  { slug: 'optician', parentSlug: 'health-beauty', title: 'بینایی‌سنجی و عینک', englishTitle: 'Optician', depth: 1, sortOrder: 706 },
  { slug: 'physiotherapist', parentSlug: 'health-beauty', title: 'فیزیوتراپی', englishTitle: 'Physiotherapist', depth: 1, sortOrder: 707 },
  { slug: 'psychologist-counselor', parentSlug: 'health-beauty', title: 'روانشناسی و مشاوره', englishTitle: 'Psychologist', depth: 1, sortOrder: 708 },
  { slug: 'nutritionist', parentSlug: 'health-beauty', title: 'متخصص تغذیه', englishTitle: 'Nutritionist', depth: 1, sortOrder: 709 },
  { slug: 'hairdresser', parentSlug: 'health-beauty', title: 'آرایشگر', englishTitle: 'Hairdresser', depth: 1, sortOrder: 710 },
  { slug: 'barber', parentSlug: 'health-beauty', title: 'آرایشگر مردانه', englishTitle: 'Barber', depth: 1, sortOrder: 711 },
  { slug: 'beauty-salon', parentSlug: 'health-beauty', title: 'سالن زیبایی و پوست', englishTitle: 'Beauty Salon', depth: 1, sortOrder: 712 },
  { slug: 'nail-technician', parentSlug: 'health-beauty', title: 'ناخن‌کار', englishTitle: 'Nail Technician', depth: 1, sortOrder: 713 },
  { slug: 'massage-therapy', parentSlug: 'health-beauty', title: 'ماساژ درمانی', englishTitle: 'Massage Therapy', depth: 1, sortOrder: 714 },
  { slug: 'midwife', parentSlug: 'health-beauty', title: 'مامایی و مراقبت بارداری', englishTitle: 'Midwife', depth: 1, sortOrder: 715 },
  { slug: 'speech-therapist', parentSlug: 'health-beauty', title: 'گفتاردرمانی', englishTitle: 'Speech Therapist', depth: 1, sortOrder: 716 },
  { slug: 'occupational-therapist', parentSlug: 'health-beauty', title: 'کاردرمانی', englishTitle: 'Occupational Therapist', depth: 1, sortOrder: 717 },
  { slug: 'specialist-clinic', parentSlug: 'health-beauty', title: 'کلینیک تخصصی پزشکی', englishTitle: 'Specialist Clinic', depth: 1, sortOrder: 718 },
  { slug: 'traditional-medicine', parentSlug: 'health-beauty', title: 'طب سنتی و گیاهی', englishTitle: 'Traditional Medicine', depth: 1, sortOrder: 719 },
  { slug: 'dental-lab', parentSlug: 'health-beauty', title: 'لابراتوار دندانسازی', englishTitle: 'Dental Lab', depth: 1, sortOrder: 720 },
  { slug: 'fitness-gym', parentSlug: 'health-beauty', title: 'باشگاه ورزشی و فیتنس', englishTitle: 'Gym', depth: 1, sortOrder: 721 },
  { slug: 'medical-equipment', parentSlug: 'health-beauty', title: 'تجهیزات پزشکی و آزمایشگاهی', englishTitle: 'Medical Equipment', depth: 1, sortOrder: 722 },

  // ── creative-media
  { slug: 'creative-media', parentSlug: null, title: 'رسانه، هنر و چاپ', englishTitle: 'Creative & Media', depth: 0, sortOrder: 800 },
  { slug: 'photographer', parentSlug: 'creative-media', title: 'عکاسی', englishTitle: 'Photographer', depth: 1, sortOrder: 801 },
  { slug: 'videographer-editor', parentSlug: 'creative-media', title: 'فیلمبرداری و تدوین', englishTitle: 'Videographer', depth: 1, sortOrder: 802 },
  { slug: 'translator', parentSlug: 'creative-media', title: 'مترجم', englishTitle: 'Translator', depth: 1, sortOrder: 803 },
  { slug: 'sign-maker', parentSlug: 'creative-media', title: 'تابلو و تبلیغات محیطی', englishTitle: 'Sign Maker', depth: 1, sortOrder: 804 },
  { slug: 'florist', parentSlug: 'creative-media', title: 'گل‌فروشی و گل‌آرایی', englishTitle: 'Florist', depth: 1, sortOrder: 805 },
  { slug: 'dj-sound', parentSlug: 'creative-media', title: 'دی‌جی و صدابرداری مراسم', englishTitle: 'DJ', depth: 1, sortOrder: 806 },
  { slug: 'music-band-events', parentSlug: 'creative-media', title: 'گروه موسیقی مراسم', englishTitle: 'Event Music', depth: 1, sortOrder: 807 },

  // ── education-coaching
  { slug: 'education-coaching', parentSlug: null, title: 'آموزش و ورزش', englishTitle: 'Education & Sports', depth: 0, sortOrder: 900 },
  { slug: 'private-tutor', parentSlug: 'education-coaching', title: 'معلم خصوصی', englishTitle: 'Private Tutor', depth: 1, sortOrder: 901 },
  { slug: 'language-teacher', parentSlug: 'education-coaching', title: 'آموزش زبان', englishTitle: 'Language Teacher', depth: 1, sortOrder: 902 },
  { slug: 'career-coach', parentSlug: 'education-coaching', title: 'مشاور تحصیلی و کنکور', englishTitle: 'Education Counselor', depth: 1, sortOrder: 903 },
  { slug: 'sports-coach', parentSlug: 'education-coaching', title: 'مربی ورزشی و باشگاه', englishTitle: 'Sports Coach', depth: 1, sortOrder: 904 },
  { slug: 'music-teacher', parentSlug: 'education-coaching', title: 'آموزش موسیقی', englishTitle: 'Music Teacher', depth: 1, sortOrder: 905 },
  { slug: 'computer-instructor', parentSlug: 'education-coaching', title: 'آموزش کامپیوتر', englishTitle: 'Computer Instructor', depth: 1, sortOrder: 906 },
  { slug: 'kindergarten', parentSlug: 'education-coaching', title: 'مهدکودک و پیش‌دبستانی', englishTitle: 'Kindergarten', depth: 1, sortOrder: 907 },
  { slug: 'art-teacher', parentSlug: 'education-coaching', title: 'آموزش هنر', englishTitle: 'Art Teacher', depth: 1, sortOrder: 908 },

  // ── food-hospitality
  { slug: 'food-hospitality', parentSlug: null, title: 'غذا و پذیرایی', englishTitle: 'Food & Hospitality', depth: 0, sortOrder: 1000 },
  { slug: 'restaurant-cafe', parentSlug: 'food-hospitality', title: 'رستوران و کافه', englishTitle: 'Restaurant & Cafe', depth: 1, sortOrder: 1001 },
  { slug: 'catering', parentSlug: 'food-hospitality', title: 'کترینگ و پذیرایی مراسم', englishTitle: 'Catering', depth: 1, sortOrder: 1002 },
  { slug: 'pastry-bakery', parentSlug: 'food-hospitality', title: 'قنادی و نانوایی', englishTitle: 'Bakery', depth: 1, sortOrder: 1003 },
  { slug: 'butcher', parentSlug: 'food-hospitality', title: 'قصابی و پروتئین', englishTitle: 'Butcher', depth: 1, sortOrder: 1004 },
  { slug: 'hotel-guesthouse', parentSlug: 'food-hospitality', title: 'هتل و اقامتگاه', englishTitle: 'Hotel', depth: 1, sortOrder: 1005 },
  { slug: 'grocery-supermarket', parentSlug: 'food-hospitality', title: 'سوپرمارکت و خواربار', englishTitle: 'Grocery', depth: 1, sortOrder: 1006 },
  { slug: 'fruit-vegetable-shop', parentSlug: 'food-hospitality', title: 'میوه‌فروشی و تره‌بار', englishTitle: 'Produce Shop', depth: 1, sortOrder: 1007 },
  { slug: 'dairy-protein-shop', parentSlug: 'food-hospitality', title: 'لبنیات و پروتئین', englishTitle: 'Dairy Shop', depth: 1, sortOrder: 1008 },
  { slug: 'tea-house', parentSlug: 'food-hospitality', title: 'چای‌خانه و قلیان', englishTitle: 'Tea House', depth: 1, sortOrder: 1009 },

  // ── events
  { slug: 'events-services', parentSlug: null, title: 'مراسم و جشن', englishTitle: 'Events', depth: 0, sortOrder: 1100 },
  { slug: 'wedding-services', parentSlug: 'events-services', title: 'خدمات عروسی', englishTitle: 'Wedding Services', depth: 1, sortOrder: 1101 },
  { slug: 'event-planner', parentSlug: 'events-services', title: 'برگزارکننده مراسم', englishTitle: 'Event Planner', depth: 1, sortOrder: 1102 },
  { slug: 'event-decoration', parentSlug: 'events-services', title: 'دکوراسیون مراسم', englishTitle: 'Event Decoration', depth: 1, sortOrder: 1103 },
  { slug: 'event-lighting-audio', parentSlug: 'events-services', title: 'نور و صدای مراسم', englishTitle: 'Event AV', depth: 1, sortOrder: 1104 },

  // ── crafts-repair
  { slug: 'crafts-repair', parentSlug: null, title: 'خیاطی و تعمیرات ظریف', englishTitle: 'Crafts & Repair', depth: 0, sortOrder: 1200 },
  { slug: 'tailor', parentSlug: 'crafts-repair', title: 'خیاطی و تعمیر لباس', englishTitle: 'Tailor', depth: 1, sortOrder: 1201 },
  { slug: 'shoe-repair', parentSlug: 'crafts-repair', title: 'کفاشی', englishTitle: 'Shoe Repair', depth: 1, sortOrder: 1202 },
  { slug: 'watch-repair', parentSlug: 'crafts-repair', title: 'ساعت‌سازی', englishTitle: 'Watch Repair', depth: 1, sortOrder: 1203 },
  { slug: 'jewelry-repair', parentSlug: 'crafts-repair', title: 'طلا و جواهرسازی', englishTitle: 'Jewelry', depth: 1, sortOrder: 1204 },
  { slug: 'goldsmith', parentSlug: 'crafts-repair', title: 'طلاسازی و ساخت زیورآلات', englishTitle: 'Goldsmith', depth: 1, sortOrder: 1205 },

  // ── pets
  { slug: 'pets-services', parentSlug: null, title: 'حیوانات خانگی', englishTitle: 'Pet Services', depth: 0, sortOrder: 1300 },
  { slug: 'pet-grooming', parentSlug: 'pets-services', title: 'آرایش و نگهداری حیوان', englishTitle: 'Pet Grooming', depth: 1, sortOrder: 1301 },
  { slug: 'pet-boarding', parentSlug: 'pets-services', title: 'پانسیون حیوانات', englishTitle: 'Pet Boarding', depth: 1, sortOrder: 1302 },
  { slug: 'pet-shop', parentSlug: 'pets-services', title: 'پت‌شاپ و فروش ملزومات', englishTitle: 'Pet Shop', depth: 1, sortOrder: 1303 },

  // ── travel-tourism
  { slug: 'travel-tourism', parentSlug: null, title: 'سفر و گردشگری', englishTitle: 'Travel', depth: 0, sortOrder: 1400 },
  { slug: 'travel-agency', parentSlug: 'travel-tourism', title: 'آژانس مسافرتی', englishTitle: 'Travel Agency', depth: 1, sortOrder: 1401 },
  { slug: 'tour-guide', parentSlug: 'travel-tourism', title: 'راهنمای تور', englishTitle: 'Tour Guide', depth: 1, sortOrder: 1402 },

  // ── security-industrial
  { slug: 'security-industrial', parentSlug: null, title: 'امنیت و صنعتی', englishTitle: 'Security & Industrial', depth: 0, sortOrder: 1500 },
  { slug: 'security-guard', parentSlug: 'security-industrial', title: 'حراست و نگهبانی', englishTitle: 'Security Guard', depth: 1, sortOrder: 1501 },
  { slug: 'fire-alarm-systems', parentSlug: 'security-industrial', title: 'اعلام حریق و اطفاء', englishTitle: 'Fire Safety', depth: 1, sortOrder: 1502 },
  { slug: 'industrial-equipment-repair', parentSlug: 'security-industrial', title: 'تعمیر ماشین‌آلات صنعتی', englishTitle: 'Industrial Repair', depth: 1, sortOrder: 1503 },
  { slug: 'generator-electrical-panel', parentSlug: 'security-industrial', title: 'برق صنعتی و ژنراتور', englishTitle: 'Industrial Electrical', depth: 1, sortOrder: 1504 },

  // ── retail-trade (shops & showrooms)
  { slug: 'retail-trade', parentSlug: null, title: 'فروشگاه و مغازه', englishTitle: 'Retail & Shops', depth: 0, sortOrder: 1650 },
  { slug: 'furniture-store', parentSlug: 'retail-trade', title: 'فروشگاه مبلمان و دکور', englishTitle: 'Furniture Store', depth: 1, sortOrder: 1651 },
  { slug: 'appliance-store', parentSlug: 'retail-trade', title: 'فروشگاه لوازم خانگی', englishTitle: 'Appliance Store', depth: 1, sortOrder: 1652 },
  { slug: 'carpet-rug-store', parentSlug: 'retail-trade', title: 'فروشگاه فرش و گلیم', englishTitle: 'Carpet Store', depth: 1, sortOrder: 1653 },
  { slug: 'clothing-store', parentSlug: 'retail-trade', title: 'فروشگاه پوشاک', englishTitle: 'Clothing Store', depth: 1, sortOrder: 1654 },
  { slug: 'shoe-store', parentSlug: 'retail-trade', title: 'فروشگاه کفش', englishTitle: 'Shoe Store', depth: 1, sortOrder: 1655 },
  { slug: 'cosmetics-store', parentSlug: 'retail-trade', title: 'فروشگاه لوازم آرایشی', englishTitle: 'Cosmetics Store', depth: 1, sortOrder: 1656 },
  { slug: 'jewelry-store', parentSlug: 'retail-trade', title: 'جواهرفروشی و سکه', englishTitle: 'Jewelry Store', depth: 1, sortOrder: 1657 },
  { slug: 'watch-store', parentSlug: 'retail-trade', title: 'فروشگاه ساعت', englishTitle: 'Watch Store', depth: 1, sortOrder: 1658 },
  { slug: 'stationery-bookstore', parentSlug: 'retail-trade', title: 'لوازم‌التحریر و کتاب', englishTitle: 'Stationery', depth: 1, sortOrder: 1659 },
  { slug: 'toy-kids-store', parentSlug: 'retail-trade', title: 'اسباب‌بازی و سیسمونی', englishTitle: 'Kids Store', depth: 1, sortOrder: 1660 },
  { slug: 'sporting-goods-store', parentSlug: 'retail-trade', title: 'لوازم ورزشی', englishTitle: 'Sporting Goods', depth: 1, sortOrder: 1661 },
  { slug: 'lighting-store', parentSlug: 'retail-trade', title: 'فروشگاه روشنایی', englishTitle: 'Lighting Store', depth: 1, sortOrder: 1662 },
  { slug: 'paint-coatings-store', parentSlug: 'retail-trade', title: 'فروشگاه رنگ و پوشش', englishTitle: 'Paint Store', depth: 1, sortOrder: 1663 },
  { slug: 'ceramic-tile-showroom', parentSlug: 'retail-trade', title: 'نمایشگاه کاشی و سرامیک', englishTitle: 'Tile Showroom', depth: 1, sortOrder: 1664 },
  { slug: 'kitchen-bath-showroom', parentSlug: 'retail-trade', title: 'نمایشگاه کابینت و سرویس', englishTitle: 'Kitchen Bath Showroom', depth: 1, sortOrder: 1665 },
  { slug: 'wholesale-distribution', parentSlug: 'retail-trade', title: 'پخش و توزیع عمده', englishTitle: 'Wholesale', depth: 1, sortOrder: 1666 },

  // ── agriculture-garden
  { slug: 'agriculture-garden', parentSlug: null, title: 'کشاورزی و باغ', englishTitle: 'Agriculture', depth: 0, sortOrder: 1680 },
  { slug: 'plant-nursery', parentSlug: 'agriculture-garden', title: 'گلخانه و گل‌فروشی عمده', englishTitle: 'Plant Nursery', depth: 1, sortOrder: 1681 },
  { slug: 'agricultural-supplies', parentSlug: 'agriculture-garden', title: 'بذر، کود و سم کشاورزی', englishTitle: 'Ag Supplies', depth: 1, sortOrder: 1682 },
  { slug: 'livestock-poultry', parentSlug: 'agriculture-garden', title: 'دامداری و طیور', englishTitle: 'Livestock', depth: 1, sortOrder: 1683 },

  // ── funeral (common real service in Iran)
  { slug: 'funeral-services', parentSlug: null, title: 'خدمات ترحیم', englishTitle: 'Funeral Services', depth: 0, sortOrder: 1600 },
  { slug: 'funeral-director', parentSlug: 'funeral-services', title: 'برگزاری مراسم ترحیم', englishTitle: 'Funeral Director', depth: 1, sortOrder: 1601 },
] as const;
