import type { LucideIcon } from 'lucide-react';
import {
  BarChart3,
  FolderTree,
  Globe2,
  MessagesSquare,
  Users,
  ListChecks,
  ShieldCheck,
  ShoppingBag,
  Briefcase,
  Building2,
  Settings2,
  GitBranch,
  Bot,
  FileText,
  AlertTriangle,
  Phone,
  Bell,
  Star,
  Wallet,
  Workflow,
  Send,
  Radar,
  ScrollText,
  HardDrive,
  Gift,
  Ticket,
  Handshake,
  SlidersHorizontal,
  LayoutGrid,
} from 'lucide-react';
import type { AdminPermissionId } from '@/config/admin-permissions';

export type SuperAdminNavItem = {
  id: string;
  label: string;
  description?: string;
  href: string;
  icon: LucideIcon;
  permission: AdminPermissionId;
};

export type SuperAdminNavGroup = {
  label: string;
  items: SuperAdminNavItem[];
};

export const SUPER_ADMIN_NAV: readonly SuperAdminNavGroup[] = [
  {
    label: 'اصلی',
    items: [
      {
        id: 'overview',
        label: 'داشبورد',
        description: 'آمار، نمودار و میانبرها',
        href: '/super-admin',
        icon: BarChart3,
        permission: 'superadmin:overview:read',
      },
      {
        id: 'analytics',
        label: 'تحلیل‌ها',
        description: 'نمودارها و روند رشد',
        href: '/super-admin/analytics',
        icon: BarChart3,
        permission: 'superadmin:analytics:read',
      },
      {
        id: 'workflow',
        label: 'صف‌های کاری',
        description: 'نمای یکپارچه moderation',
        href: '/super-admin/workflow',
        icon: Workflow,
        permission: 'ops:workflow:read',
      },
    ],
  },
  {
    label: 'مدیریت محتوا',
    items: [
      {
        id: 'categories',
        label: 'دسته‌بندی نیازها',
        description: 'نمایش mega menu نیازها (Header، Intake، مرور)',
        href: '/super-admin/categories',
        icon: FolderTree,
        permission: 'taxonomy:categories:read',
      },
      {
        id: 'business-occupations',
        label: 'دسته‌بندی کسب‌وکار',
        description: 'نمایش منوی مرور کسب‌وکار و حرفه‌ها',
        href: '/super-admin/business-occupations',
        icon: Briefcase,
        permission: 'taxonomy:business-occupations:read',
      },
      {
        id: 'online-stores',
        label: 'فروشگاه‌های اینترنتی',
        description: 'نمایش ریشه فروشگاه آنلاین در مرور کسب‌وکار',
        href: '/super-admin/online-stores',
        icon: ShoppingBag,
        permission: 'taxonomy:online-stores:read',
      },
      {
        id: 'locations',
        label: 'مکان‌ها',
        description: 'استان، شهر و محله',
        href: '/super-admin/locations',
        icon: Globe2,
        permission: 'geo:locations:read',
      },
    ],
  },
  {
    label: 'بازار',
    items: [
      {
        id: 'requests',
        label: 'نیازها',
        description: 'صف و بازبینی نیازها',
        href: '/super-admin/requests',
        icon: ListChecks,
        permission: 'market:requests:read',
      },
      {
        id: 'proposals',
        label: 'پیشنهادها',
        description: 'مدیریت پیشنهادهای متخصص',
        href: '/super-admin/proposals',
        icon: Handshake,
        permission: 'market:proposals:read',
      },
      {
        id: 'businesses',
        label: 'کسب‌وکارها',
        description: 'مدیریت پروفایل متخصص‌ها',
        href: '/super-admin/businesses',
        icon: Building2,
        permission: 'market:businesses:read',
      },
      {
        id: 'filings',
        label: 'فایلینگ',
        description: 'فایل‌های منطقه برای میزکار مشاوران',
        href: '/super-admin/filings',
        icon: LayoutGrid,
        permission: 'market:filings:read',
      },
      {
        id: 'outreach',
        label: 'Outreach',
        description: 'ارسال lead به کسب‌وکارها',
        href: '/super-admin/outreach',
        icon: Send,
        permission: 'market:outreach:read',
      },
      {
        id: 'need-alerts',
        label: 'Alertهای مرور',
        description: 'اشتراک‌های مرور نیاز',
        href: '/super-admin/need-alerts',
        icon: Radar,
        permission: 'market:alerts:read',
      },
    ],
  },
  {
    label: 'CRM و ارتباطات',
    items: [
      {
        id: 'users',
        label: 'کاربران',
        description: 'وضعیت حساب‌ها و نقش‌ها',
        href: '/super-admin/users',
        icon: Users,
        permission: 'crm:users:read',
      },
      {
        id: 'reports',
        label: 'گزارش تخلف',
        description: 'صف رسیدگی به گزارش‌ها',
        href: '/super-admin/reports',
        icon: AlertTriangle,
        permission: 'content:reports:read',
      },
      {
        id: 'messages',
        label: 'بازبینی چت‌ها',
        description: 'مشاهده و کنترل گفتگوها',
        href: '/super-admin/messages',
        icon: MessagesSquare,
        permission: 'comms:messages:read',
      },
      {
        id: 'voice-calls',
        label: 'تماس صوتی',
        description: 'مانیتoring تماس‌ها',
        href: '/super-admin/voice-calls',
        icon: Phone,
        permission: 'comms:voice:read',
      },
      {
        id: 'notifications',
        label: 'اعلان‌ها',
        description: 'مشاهده و broadcast',
        href: '/super-admin/notifications',
        icon: Bell,
        permission: 'comms:notifications:read',
      },
      {
        id: 'reviews',
        label: 'نظرات',
        description: 'بازبینی نظرات',
        href: '/super-admin/reviews',
        icon: Star,
        permission: 'content:reviews:read',
      },
      {
        id: 'blog',
        label: 'بلاگ',
        description: 'مدیریت مقالات',
        href: '/super-admin/blog',
        icon: FileText,
        permission: 'content:blog:read',
      },
    ],
  },
  {
    label: 'مالی',
    items: [
      {
        id: 'billing',
        label: 'تراکنش‌ها',
        description: 'کیف پول و پرداخت',
        href: '/super-admin/billing',
        icon: Wallet,
        permission: 'billing:transactions:read',
      },
    ],
  },
  {
    label: 'سیستم',
    items: [
      {
        id: 'system',
        label: 'نقش‌ها و دسترسی‌ها',
        description: 'مدیریت کارمندان و مجوزها',
        href: '/super-admin/system',
        icon: ShieldCheck,
        permission: 'rbac:roles:read',
      },
      {
        id: 'audit',
        label: 'گزارش تغییرات',
        description: 'Audit log اقدامات admin',
        href: '/super-admin/audit',
        icon: ScrollText,
        permission: 'audit:read',
      },
      {
        id: 'files',
        label: 'فایل‌ها',
        description: 'آپلودها و دارایی‌ها',
        href: '/super-admin/files',
        icon: HardDrive,
        permission: 'ops:files:read',
      },
      {
        id: 'intake-migration',
        label: 'مهاجرت Intake',
        description: 'کنترل Legacy vs Canonical',
        href: '/super-admin/system/intake-migration',
        icon: GitBranch,
        permission: 'ops:intake-migration:read',
      },
      {
        id: 'intake-ai-evaluation',
        label: 'ارزیابی AI Intake',
        description: 'Accuracy و KPI مدل Gemma',
        href: '/super-admin/system/intake-ai-evaluation',
        icon: Bot,
        permission: 'ops:intake-ai-evaluation:read',
      },
      {
        id: 'intake-training',
        label: 'داده آموزشی Intake',
        description: 'Capture، بازبینی، Gold Dataset',
        href: '/super-admin/system/intake-training',
        icon: Bot,
        permission: 'ops:intake-training:read',
      },
      {
        id: 'intake-field-specs',
        label: 'فیلدهای Intake',
        description: 'CRUD فیلد، نسخه، rollback، export',
        href: '/super-admin/system/intake-field-specs',
        icon: SlidersHorizontal,
        permission: 'ops:intake-field-specs:read',
      },
      {
        id: 'referrals',
        label: 'ارجاع‌ها',
        description: 'آمار referral',
        href: '/super-admin/referrals',
        icon: Gift,
        permission: 'growth:referrals:read',
      },
      {
        id: 'coupons',
        label: 'کوپن‌ها',
        description: 'مدیریت کوپن',
        href: '/super-admin/coupons',
        icon: Ticket,
        permission: 'growth:coupons:read',
      },
      {
        id: 'settings',
        label: 'تنظیمات',
        description: 'پیکربندی و سیاست‌ها',
        href: '/super-admin/settings',
        icon: Settings2,
        permission: 'ops:settings:write',
      },
    ],
  },
] as const;
