export class SmartMatchingError extends Error {
  constructor(
    message: string,
    readonly code: string,
    readonly status = 400
  ) {
    super(message);
    this.name = 'SmartMatchingError';
  }
}

export const SMART_MATCHING_CODES = {
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
  PRIVATE_LEAD_CAP_REACHED: 'PRIVATE_LEAD_CAP_REACHED',
  MAX_SESSIONS_REACHED: 'MAX_SESSIONS_REACHED',
  NEED_NOT_PRIVATE: 'NEED_NOT_PRIVATE',
  UNAUTHORIZED_SESSION: 'UNAUTHORIZED_SESSION',
  ALREADY_RESOLVED: 'ALREADY_RESOLVED',
  ALREADY_PENDING_VERIFICATION: 'ALREADY_PENDING_VERIFICATION',
  WINNER_NOT_IN_ACTIVE_SESSIONS: 'WINNER_NOT_IN_ACTIVE_SESSIONS',
  REFUND_ALREADY_ISSUED: 'REFUND_ALREADY_ISSUED',
  OUTREACH_NOT_SENT: 'OUTREACH_NOT_SENT',
  UNPAID_LEAD: 'UNPAID_LEAD',
} as const;
