/**
 * Per-job icons for occupation mega menu (layer 2).
 * Sector color is unchanged; each job gets a distinct icon.
 */
import type { ElementType } from 'react';
import {
  Ambulance,
  Apple,
  Armchair,
  Baby,
  Banknote,
  Bath,
  Bike,
  BookOpen,
  Box,
  Briefcase,
  Building,
  Building2,
  Bug,
  Bus,
  Cake,
  Calculator,
  Calendar,
  Camera,
  Car,
  CarFront,
  ChefHat,
  Circle,
  Coffee,
  Compass,
  Cpu,
  Crown,
  Dog,
  DoorOpen,
  Droplets,
  Dumbbell,
  Factory,
  FileText,
  Flame,
  Flower2,
  Footprints,
  Fuel,
  Gamepad2,
  Gavel,
  Gem,
  Glasses,
  GraduationCap,
  Hammer,
  HandCoins,
  HardHat,
  Headphones,
  Heart,
  HeartPulse,
  Home,
  Hotel,
  Key,
  Lamp,
  Landmark,
  Languages,
  Laptop,
  Layers,
  Leaf,
  Lightbulb,
  Map,
  Megaphone,
  Mic2,
  Monitor,
  Mountain,
  Music,
  Paintbrush,
  Palette,
  PawPrint,
  PenTool,
  Pill,
  Plane,
  Printer,
  Recycle,
  Refrigerator,
  Rocket,
  Ruler,
  Scale,
  Scissors,
  Shield,
  Ship,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Snowflake,
  Sofa,
  Sparkles,
  Sprout,
  Stethoscope,
  Store,
  Sun,
  Syringe,
  Tent,
  Train,
  Trees,
  Truck,
  Tv,
  Utensils,
  Video,
  Wallet,
  Warehouse,
  WashingMachine,
  Watch,
  Waves,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react';

/** Semantic icon per occupation slug (Iran market jobs). */
const OCCUPATION_JOB_ICONS: Record<string, LucideIcon> = {
  'real-estate-agent': Building2,
  'interior-designer': Sofa,
  architect: PenTool,
  'property-manager': Building,
  'facility-maintenance': Wrench,
  'elevator-technician': Layers,
  'land-surveyor': Ruler,
  'official-appraiser': Scale,
  'gate-automation': DoorOpen,
  cleaner: Sparkles,
  'moving-company': Truck,
  'appliance-repair': WashingMachine,
  locksmith: Key,
  'gardener-landscaping': Trees,
  'pest-control': Bug,
  'laundry-dry-clean': Shirt,
  'carpet-cleaning': Layers,
  'upholstery-furniture': Armchair,
  'curtain-blinds': Home,
  'water-tank-cleaning': Droplets,
  'pool-maintenance': Waves,
  'elderly-home-care': Heart,
  'nanny-childcare': Baby,
  plumber: Droplets,
  electrician: Zap,
  'hvac-technician': Snowflake,
  'painter-decorator': Paintbrush,
  tiler: Layers,
  carpenter: Hammer,
  'general-contractor': HardHat,
  mason: Building,
  'welder-metalwork': Flame,
  glazier: Monitor,
  roofer: Home,
  'aluminum-windows': DoorOpen,
  'parquet-flooring': Layers,
  'stone-marble': Mountain,
  'demolition-excavation': Hammer,
  scaffolding: Warehouse,
  'solar-panel-installer': Sun,
  waterproofing: Droplets,
  'kitchen-countertop': ChefHat,
  'steel-structure': Factory,
  'building-materials-supplier': Warehouse,
  'hardware-tools-store': Wrench,
  'plasterboard-drywall': Layers,
  'web-developer': Laptop,
  'graphic-designer': Palette,
  'seo-digital-marketing': Megaphone,
  'mobile-repair': Smartphone,
  'computer-repair': Cpu,
  'it-support': Monitor,
  'ui-ux-designer': PenTool,
  'cctv-security-systems': Shield,
  'social-media-manager': Megaphone,
  'printing-copy-center': Printer,
  'mobile-phone-store': Smartphone,
  'computer-store': Laptop,
  'electronics-store': Tv,
  'auto-mechanic': Wrench,
  'auto-body-paint': Paintbrush,
  'auto-electric': Zap,
  'tire-wheel-service': Circle,
  'car-wash-detailing': Droplets,
  'motorcycle-mechanic': Bike,
  'towing-roadside': Truck,
  'courier-delivery': Box,
  'freight-trucking': Truck,
  'driver-taxi': Car,
  'driving-instructor': CarFront,
  'car-dealership': CarFront,
  'motorcycle-dealership': Bike,
  'auto-parts-store': Wrench,
  'car-rental-agency': Key,
  'auto-glass': Monitor,
  'auto-upholstery': Armchair,
  'auto-accessories-shop': Headphones,
  'diesel-mechanic': Fuel,
  'crane-heavy-machinery': Factory,
  lawyer: Gavel,
  accountant: Calculator,
  'tax-advisor': FileText,
  'insurance-agent': Shield,
  'financial-advisor': Banknote,
  'notary-legal-docs': FileText,
  'recruitment-hr': Briefcase,
  'management-consultant': Compass,
  'customs-broker': Ship,
  'import-export-trader': Plane,
  dentist: Stethoscope,
  'general-practitioner': Stethoscope,
  pharmacy: Pill,
  'medical-lab': Syringe,
  veterinarian: PawPrint,
  optician: Glasses,
  physiotherapist: HeartPulse,
  'psychologist-counselor': Heart,
  nutritionist: Apple,
  hairdresser: Scissors,
  barber: Scissors,
  'beauty-salon': Sparkles,
  'nail-technician': Sparkles,
  'massage-therapy': HandCoins,
  midwife: Baby,
  'speech-therapist': Mic2,
  'occupational-therapist': HeartPulse,
  'specialist-clinic': Stethoscope,
  'traditional-medicine': Leaf,
  'dental-lab': Stethoscope,
  'fitness-gym': Dumbbell,
  'medical-equipment': Stethoscope,
  photographer: Camera,
  'videographer-editor': Video,
  translator: Languages,
  'sign-maker': Lightbulb,
  florist: Flower2,
  'dj-sound': Music,
  'music-band-events': Music,
  'private-tutor': BookOpen,
  'language-teacher': Languages,
  'career-coach': GraduationCap,
  'sports-coach': Dumbbell,
  'music-teacher': Music,
  'computer-instructor': Laptop,
  kindergarten: Baby,
  'art-teacher': Palette,
  'restaurant-cafe': Utensils,
  catering: ChefHat,
  'pastry-bakery': Cake,
  butcher: Utensils,
  'hotel-guesthouse': Hotel,
  'grocery-supermarket': ShoppingCart,
  'fruit-vegetable-shop': Apple,
  'dairy-protein-shop': Coffee,
  'tea-house': Coffee,
  'wedding-services': Crown,
  'event-planner': Calendar,
  'event-decoration': Sparkles,
  'event-lighting-audio': Lightbulb,
  tailor: Scissors,
  'shoe-repair': Footprints,
  'watch-repair': Watch,
  'jewelry-repair': Gem,
  goldsmith: Gem,
  'pet-grooming': Dog,
  'pet-boarding': PawPrint,
  'pet-shop': Dog,
  'travel-agency': Plane,
  'tour-guide': Map,
  'security-guard': Shield,
  'fire-alarm-systems': Flame,
  'industrial-equipment-repair': Factory,
  'generator-electrical-panel': Zap,
  'funeral-director': Briefcase,
  'furniture-store': Sofa,
  'appliance-store': Refrigerator,
  'carpet-rug-store': Layers,
  'clothing-store': Shirt,
  'shoe-store': Footprints,
  'cosmetics-store': Sparkles,
  'jewelry-store': Gem,
  'watch-store': Watch,
  'stationery-bookstore': BookOpen,
  'toy-kids-store': Gamepad2,
  'sporting-goods-store': Dumbbell,
  'lighting-store': Lamp,
  'paint-coatings-store': Paintbrush,
  'ceramic-tile-showroom': Layers,
  'kitchen-bath-showroom': Bath,
  'wholesale-distribution': Warehouse,
  'plant-nursery': Sprout,
  'agricultural-supplies': Sprout,
  'livestock-poultry': Tent,
};

const ICON_POOL: LucideIcon[] = [
  Wrench, Hammer, Car, Home, Laptop, Heart, Camera, Truck, Scissors, BookOpen,
  Palette, Shield, Plane, Store, Utensils, Music, GraduationCap, Sparkles, Zap, Droplets,
  Building2, Gem, Dog, Coffee, ChefHat, Factory, Trees, Paintbrush, Megaphone,
  Stethoscope, Briefcase, Wallet, Map, Lightbulb, Flower2, Bike, Monitor, Cpu, Smartphone,
  HardHat, Rocket, Recycle, Train, Bus, Tent, Compass, Gavel,
  Calculator, Banknote, Fuel, Layers, Sun, Snowflake, Waves, Armchair, Sofa, Refrigerator,
  ShoppingCart, Apple, Crown, Footprints, Box, Bath, Hotel, Sprout, Ambulance, HandCoins,
  Ship, Landmark, Printer, Headphones, Gamepad2, Watch, Calendar, Bug, Circle, Key,
];

function hashSlug(slug: string): number {
  let h = 0;
  for (let i = 0; i < slug.length; i++) {
    h = (h * 31 + slug.charCodeAt(i)) >>> 0;
  }
  return h;
}

export function getOccupationJobIcon(slug: string): ElementType {
  return OCCUPATION_JOB_ICONS[slug] ?? ICON_POOL[hashSlug(slug) % ICON_POOL.length];
}
