/**
 * Per-leaf icons for online store mega menu.
 */
import type { ElementType } from 'react';
import {
  Baby,
  Bike,
  BookOpen,
  Box,
  Camera,
  Car,
  Cpu,
  Flower2,
  Gamepad2,
  Gem,
  Gift,
  Glasses,
  Globe,
  Headphones,
  Heart,
  Home,
  Laptop,
  Leaf,
  Monitor,
  Music,
  Package,
  Palette,
  PawPrint,
  PenTool,
  Plane,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Store,
  Sun,
  Tent,
  Truck,
  UtensilsCrossed,
  Watch,
  Wrench,
  type LucideIcon,
} from 'lucide-react';

const ICONS: Record<string, LucideIcon> = {
  'online-clothing-apparel': Shirt,
  'online-footwear': ShoppingBag,
  'online-traditional-clothing': Sparkles,
  'online-hijab-modest-fashion': Shirt,
  'online-bags-leather': ShoppingBag,
  'online-fashion-accessories': Sparkles,
  'online-costume-jewelry': Gem,
  'online-gold-silver-jewelry': Gem,
  'online-watches': Watch,
  'online-gems-stones': Gem,
  'online-mobile-tablet': Smartphone,
  'online-laptop-computer': Laptop,
  'online-computer-parts': Cpu,
  'online-gaming-console': Gamepad2,
  'online-audio-video': Headphones,
  'online-camera-photography': Camera,
  'online-digital-accessories': Monitor,
  'online-smart-home-iot': Home,
  'online-home-appliances': Home,
  'online-small-kitchen-appliances': UtensilsCrossed,
  'online-cookware-tableware': UtensilsCrossed,
  'online-home-decor': Palette,
  'online-furniture': Home,
  'online-bedding-mattress': Home,
  'online-carpet-rug': Home,
  'online-lighting': Sun,
  'online-curtains-textiles': Shirt,
  'online-cosmetics-skincare': Sparkles,
  'online-perfume-fragrance': Sparkles,
  'online-haircare-salon-supplies': Sparkles,
  'online-personal-hygiene': Heart,
  'online-health-supplements': Heart,
  'online-medical-equipment-consumer': Heart,
  'online-herbal-traditional': Leaf,
  'online-supermarket-grocery': ShoppingCart,
  'online-fresh-produce': Leaf,
  'online-dried-nuts-saffron': Package,
  'online-dairy-bakery': UtensilsCrossed,
  'online-organic-health-food': Leaf,
  'online-beverages': UtensilsCrossed,
  'online-baby-gear': Baby,
  'online-toys': Gamepad2,
  'online-kids-clothing': Baby,
  'online-maternity': Baby,
  'online-sporting-goods': Bike,
  'online-outdoor-camping': Tent,
  'online-travel-luggage': Plane,
  'online-bicycle-scooter': Bike,
  'online-auto-parts': Car,
  'online-motorcycle-parts': Bike,
  'online-car-accessories': Car,
  'online-tires': Car,
  'online-books': BookOpen,
  'online-stationery': PenTool,
  'online-music-instruments': Music,
  'online-art-supplies': Palette,
  'online-pet-supplies': PawPrint,
  'online-plants-seeds': Flower2,
  'online-garden-tools': Leaf,
  'online-handicrafts-traditional': Palette,
  'online-art-collectibles': Palette,
  'online-flowers-gifts': Flower2,
  'online-religious-cultural': BookOpen,
  'online-party-supplies': Gift,
  'online-office-supplies': PenTool,
  'online-industrial-tools': Wrench,
  'online-building-materials': Wrench,
  'online-packaging-printing': Box,
  'online-eyewear-optical': Glasses,
  'online-security-cctv': Monitor,
  'online-solar-energy-products': Sun,
  'online-sewing-fabric': Shirt,
  'online-tailoring-supplies': PenTool,
  'online-multi-category-marketplace': Store,
  'online-single-brand-store': Store,
  'online-dropshipping': Truck,
  'online-social-commerce': Globe,
  'online-b2b-wholesale': Package,
};

const DEFAULT = ShoppingBag;

export function getOnlineStoreLeafIcon(slug: string): ElementType {
  return ICONS[slug] ?? DEFAULT;
}
